### ISSUE TITLE
Tick图支持

### ISSUE THREAD

**Issue by somewheve** [liihuu/KLineChart#102]
老哥 我在尝试在我开源项目[ctpbee](https://github.com/ctpbee/ctpbee)做回测 集成 想找一个图表， 然后看到这个好像很清晰。 想问问你这个支持tick图嘛 速度咋样啊  

k线图我看了很完美  可以弄

**Comment by somewheve** [comment]
我想回测同时支持k线和tick图

**Comment by liihuu** [comment]
我不太清楚你想要的tick图是什么样的

**Comment by somewheve** [comment]
https://opensource2.zealink.com/hqweb/demo/phone24.html

**Comment by liihuu** [comment]
可以用自定义技术指标的自定义绘制实现。

**Comment by somewheve** [comment]
有时间了  准备接入支持了  有一个问题或者说需求  

能支持键盘左移右移吗 比如按照ctrl  + -> 就可以右移

**Comment by liihuu** [comment]
快捷键目前只支持简单的左移右移和缩放
https://github.com/liihuu/KLineChart/blob/master/docs/zh-CN/hot-key.md

**Comment by somewheve** [comment]
ok  谢谢拉
