### ISSUE TITLE
_xAxis.convertToPixel incorrect values

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#104]
graphic mark is return incorrect value with
_xAxis.convertToPixel
![image](https://user-images.githubusercontent.com/25048796/113227499-35fe1f00-9269-11eb-91ce-995b0e14ea4c.png)

with  _**y**Axis.convertToPixel  its ok

**Comment by danielmalencar** [comment]
Expected value is 740,449 ....

**Comment by danielmalencar** [comment]
Can you help me, please? @liihuu

**Comment by liihuu** [comment]
The internal xAxis.convertToPixel parameter is dataIndex, not timestamp.
