### ISSUE TITLE
How to get a moved mark's new price/timestamp/dataIndex?

### ISSUE THREAD

**Issue by fuzzthink** [liihuu/KLineChart#105]
After moving a mark, is there any way to get the new price/timestamp/dataIndex from the mark id? If not, shouldn't it? 

Alternative I can get `clientX/Y` or `pageX/Y` from `onPressedMove`. I see `XAxis.convertFromPixel()` seems to be able to do the conversion, but `XAxis` doesn't seem to be exported.

**Comment by danielmalencar** [comment]
I can access with ._xAxis

**Comment by fuzzthink** [comment]
How do you get the mark instance? createGraphicMark returns just the id.

**Comment by danielmalencar** [comment]
My solution is
function getGraphicMark(id)
{
    var markers =chart._chartPane._candlePane._chartData.graphicMarks();
    for (var x=0;x<markers .length;x++)
    {
        if(markers [x]._id==id)
        return markers[x]
    }

    return false
}

**Comment by fuzzthink** [comment]
Good hack, thanks! For reference, it's ._tpPoints, not _xAxis.

@liihuu Seems like there should be APIs to get around these types of hacks. Or at least, maybe think about createGraphicMark return the instance instead of id? Also, expose something like getPriceTime() to return ._tpPoints?

**Comment by liihuu** [comment]
> My solution is
> function getGraphicMark(id)
> {
> var markers =chart._chartPane._candlePane._chartData.graphicMarks();
> for (var x=0;x<markers .length;x++)
> {
> if(markers [x]._id==id)
> return markers[x]
> }
> 
> ```
> return false
> ```
> 
> }

I suggest that it is best not to use this way to get it, so that some attributes are directly modified, and it may not be able to redraw in real time.

**Comment by liihuu** [comment]
> Good hack, thanks! For reference, it's ._tpPoints, not _xAxis.
> 
> @liihuu Seems like there should be APIs to get around these types of hacks. Or at least, maybe think about createGraphicMark return the instance instead of id? Also, expose something like getPriceTime() to return ._tpPoints?

This is a good suggestion, but currently only read-only instances can be returned.

**Comment by danielmalencar** [comment]
> > Good hack, thanks! For reference, it's ._tpPoints, not _xAxis.
> > @liihuu Seems like there should be APIs to get around these types of hacks. Or at least, maybe think about createGraphicMark return the instance instead of id? Also, expose something like getPriceTime() to return ._tpPoints?
> 
> This is a good suggestion, but currently only read-only instances can be returned.

Another alternative?

**Comment by danielmalencar** [comment]
Thanks for the amazing library! When I win the first money I will donate a percentage to you @liihuu

**Comment by fuzzthink** [comment]
> I suggest that it is best not to use this way to get it, so that some attributes are directly modified, and it may not be able to redraw in real time.

But there seems to be no other way right now to get the mark instance. For what it's worth, I made a "chart interface" to make this a bit hacky.  Hopefully the API will expose these in the future so I can throw this code away:

```javascript
const ChartIF = (chart) => {
  /**
   * @returns {GraphicMark}
   */
  const getMark = (id) => {
    return chart._chartPane._candlePane._chartData.graphicMarks()
      .find(o => o._id === id)
  }

  return {
    chart,
    getMark,
    getMarkPoints: (id) => getMark(id)._tpPoints,
  }
}
export default ChartIF
```

**Comment by liihuu** [comment]
Version 7.1.0    api `getGraphicMark`
