### ISSUE TITLE
Add support for adding arbitrary content to the graph that follows the graph zoom and scroll position

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#107]
My use-case would be to add icons to the graph that have popups when clicked or hovered with additional information. This could be used to annotate splits and dividends, or other arbitrary annotations. Currently I can create arbitrary drawings that follow the graph position with custom indicators, but I can't interact with them since they are just canvas items. Alternatively I could layer anything I want on top of the graph, but then the items won't follow the graph position since there is no way to connect in to the graph position functions. Exposing some sort of "graph position update" callback might be sufficient because then I could just update the object positions based on the return values from that function.

**Comment by liihuu** [comment]
I am trying to do same features, see #81

**Comment by DeeeeLAN** [comment]
Ah, I see that now. I would definitely be in favor of letting the content be arbitrary if at all possible, that way I can use custom tooltips with my CSS library instead of the standard tooltips provided by html. One suggestion would be to look at how https://github.com/rrag/react-stockcharts implemented it, they use a hybrid canvas/svg approach that lets you get the best of both worlds.

**Comment by liihuu** [comment]
Version 7.1.0 has been supported.
