### ISSUE TITLE
Contribution of Diagonal Line in Fibonacci

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#109]
I understand that you don't have a lot of free time, so I made a small contribution. Thanks!
#108

**Comment by danielmalencar** [comment]
![image](https://user-images.githubusercontent.com/25048796/114262335-e4b30580-99b5-11eb-9cf0-c2b6749476d4.png)

**Comment by liihuu** [comment]
Can it be used as a line drawing tool instead of modifying on the original basis.
