### ISSUE TITLE
Create custom popup text

### ISSUE THREAD

**Issue by baghuz** [liihuu/KLineChart#110]
Hello, is not an issue. But i need sample code to create this one 

![Screen Shot 2021-04-11 at 01 24 12](https://user-images.githubusercontent.com/10344295/114280765-11722600-9a65-11eb-9651-3326f8aaff6a.png)
 
Please help sir :D

**Comment by liihuu** [comment]
Api `subscribeAction`.

**Comment by baghuz** [comment]
![Screen Shot 2021-04-12 at 20 34 05](https://user-images.githubusercontent.com/10344295/114402901-7d23d280-9bce-11eb-9b35-e4b1e9122760.png)

Got it! Thanks sir
