### ISSUE TITLE
Bollinger Bands decimal places params

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#111]
Bollinger bands do not accept parameters with decimal places,
example: [20,2.5].
He always converts to [20.2]
This reduces the accuracy in many cases

![image](https://user-images.githubusercontent.com/25048796/114292134-c35c2300-9a62-11eb-83d2-8c76dbe1a1c7.png)
![image](https://user-images.githubusercontent.com/25048796/114292151-e090f180-9a62-11eb-850f-6ad60402b7dc.png)

**Comment by liihuu** [comment]
Calculation parameters only accept integers, even decimals will be formatted. If chart to support decimals, I need to consider its rationality.

**Comment by alonexy** [comment]
我也遇到这个问题，不支持小数位对指标计算影响较大

**Comment by danielmalencar** [comment]
Please, reconsider @liihuu

**Comment by liihuu** [comment]
> Please, reconsider @liihuu

I'm thinking about how to limit it, because not all calculation parameters require decimals.

**Comment by liihuu** [comment]
Version 7.1.0 has been supported.
