### ISSUE TITLE
Grid spacing

### ISSUE THREAD

**Issue by ghost** [liihuu/KLineChart#113]
How to change the  space between vertical grid lines to 5 candles inside in max zoom?
![image](https://user-images.githubusercontent.com/25048796/115090932-8d002700-9eec-11eb-9900-199edfd76853.png)

**Comment by danielmalencar** [comment]
@liihuu  Can yo help me, please?

**Comment by liihuu** [comment]
Now it is calculated by the chart itself, and the tail setting is not yet supported.
