### ISSUE TITLE
文档描述的数据载入格式和sample code  js版本 不一致 以哪个为准    

### ISSUE THREAD

**Issue by somewheve** [liihuu/KLineChart#114]
同理衍生的问题  载入图形标记 如何控制填 字符串格式的下表 还是timestamp 

如题

**Comment by somewheve** [comment]
还有一个问题  中国的蜡烛图 是红色是涨 以及跌是绿色 能否支持一个快速反转颜色的API 以支持这个

**Comment by liihuu** [comment]
+ 要确保timestamp传入到图表的是number类型
+ 不管是红涨绿跌，还是绿涨红跌，通过样式配置即可

**Comment by somewheve** [comment]
那么 配置文本标记打点 有demo吗 我找了一圈 好像没看到.....   比如比较多开 多平  空开 空平的例子

**Comment by liihuu** [comment]
https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/CustomCandleMarkKLineChart.jsx

**Comment by somewheve** [comment]
谢谢
