### ISSUE TITLE
Draw Ask and Bid

### ISSUE THREAD

**Issue by davidPardoC** [liihuu/KLineChart#115]
I have seen your example page , specifically to this part , i would like to know if there is some way to plot that prices apart from technical indicator, for example i`m pulling ask and bid from websockets , and I would like to plot as a current price indicator or plotting lines parallel to the current price line.
![image](https://user-images.githubusercontent.com/43886292/115243645-c2716400-a0e8-11eb-9844-e79ac62ce601.png)
Is there any  aproach to follow to achieve what I want?.

Also i'm trying to do something like this, to achieve buy sell points 
![image](https://user-images.githubusercontent.com/43886292/115244822-ee411980-a0e9-11eb-85c2-d1ef071ed19a.png)
I don´t know if subscribeAction is the right way to do this. PD:There is no source code for the sample page? i think is very complete and ith can solve the most of the doubts.

**Comment by somewheve** [comment]
also have this question, could you provide the code of the simple page about how to mark point?

**Comment by danielmalencar** [comment]
> also have this question, could you provide the code of the simple page about how to mark point?

Please, see: 
https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/CustomCandleMarkKLineChart.jsx

**Comment by somewheve** [comment]
Can you explain the meaning of 
```
 const startX = coordinate.x + 10
        const startY = coordinate.close
        ctx.beginPath()
        ctx.moveTo(startX, startY)
        ctx.lineTo(startX + 10, startY - 10)
        ctx.lineTo(startX + 10 + textWidth + 10, startY - 10)
        ctx.lineTo(startX + 10 + textWidth + 10, startY + 10)
        ctx.lineTo(startX + 10, startY + 10)
        ctx.closePath()
        ctx.fill()
?

I try to get this effect 
https://user-images.githubusercontent.com/43886292/115244822-ee411980-a0e9-11eb-85c2-d1ef071ed19a.png

**Comment by liihuu** [comment]
This is a piece of drawing code.

**Comment by liihuu** [comment]
> Can you explain the meaning of
> 
> ```
>  const startX = coordinate.x + 10
>         const startY = coordinate.close
>         ctx.beginPath()
>         ctx.moveTo(startX, startY)
>         ctx.lineTo(startX + 10, startY - 10)
>         ctx.lineTo(startX + 10 + textWidth + 10, startY - 10)
>         ctx.lineTo(startX + 10 + textWidth + 10, startY + 10)
>         ctx.lineTo(startX + 10, startY + 10)
>         ctx.closePath()
>         ctx.fill()
> ?
> 
> I try to get this effect 
> https://user-images.githubusercontent.com/43886292/115244822-ee411980-a0e9-11eb-85c2-d1ef071ed19a.png
> ```

This is a piece of drawing code.

**Comment by somewheve** [comment]
...... I know that, but I do not know the effect of the code 
`
ctx.lineTo(startX + 10, startY + 10)
`
 and it executes four times and no annotations. 

I think providing a high-level API is necessary,  some users are nonprofessional front end developer,  
for example 
`
chart.add_mark_text("hello world",   [text_width, text_height,  [offset_x, offset_y] )
`

`offset_x` and `offset_y` are the offset between and kline center and the text center.

**Comment by danielmeloalencar** [comment]
> ...... I know that, but I do not know the effect of the code
> `ctx.lineTo(startX + 10, startY + 10)`
> and it executes four times and no annotations.
> 
> I think providing a high-level API is necessary, some users are nonprofessional front end developer,
> for example
> `chart.add_mark_text("hello world", [text_width, text_height, [offset_x, offset_y] )`
> 
> `offset_x` and `offset_y` are the offset between and kline center and the text center.

https://www.w3schools.com/tags/canvas_lineto.asp

**Comment by somewheve** [comment]
got this

**Comment by somewheve** [comment]
> > ...... I know that, but I do not know the effect of the code
> > `ctx.lineTo(startX + 10, startY + 10)`
> > and it executes four times and no annotations.
> > I think providing a high-level API is necessary, some users are nonprofessional front end developer,
> > for example
> > `chart.add_mark_text("hello world", [text_width, text_height, [offset_x, offset_y] )`
> > `offset_x` and `offset_y` are the offset between and kline center and the text center.
> 
> https://www.w3schools.com/tags/canvas_lineto.asp

got this

**Comment by liihuu** [comment]
> > > ...... I know that, but I do not know the effect of the code
> > > `ctx.lineTo(startX + 10, startY + 10)`
> > > and it executes four times and no annotations.
> > > I think providing a high-level API is necessary, some users are nonprofessional front end developer,
> > > for example
> > > `chart.add_mark_text("hello world", [text_width, text_height, [offset_x, offset_y] )`
> > > `offset_x` and `offset_y` are the offset between and kline center and the text center.
> > 
> > 
> > https://www.w3schools.com/tags/canvas_lineto.asp
> 
> got this, and do you know how to how to achieve this effect. ? I am just a ROOKIE in front end development
> 
> https://user-images.githubusercontent.com/43886292/115244822-ee411980-a0e9-11eb-85c2-d1ef071ed19a.png

Version 7.1.0 will release a new feature, `annotation`, it can do some event handling.

**Comment by somewheve** [comment]
Looking forward to new features and hope to get some examples about how to draw mark point.

I have run this example  but can't get the effect same as  https://user-images.githubusercontent.com/43886292/115244822-ee411980-a0e9-11eb-85c2-d1ef071ed19a.png

**Comment by davidPardoC** [comment]
> > > > ...... I know that, but I do not know the effect of the code
> > > > `ctx.lineTo(startX + 10, startY + 10)`
> > > > and it executes four times and no annotations.
> > > > I think providing a high-level API is necessary, some users are nonprofessional front end developer,
> > > > for example
> > > > `chart.add_mark_text("hello world", [text_width, text_height, [offset_x, offset_y] )`
> > > > `offset_x` and `offset_y` are the offset between and kline center and the text center.
> > > 
> > > 
> > > https://www.w3schools.com/tags/canvas_lineto.asp
> > 
> > 
> > got this, and do you know how to how to achieve this effect. ? I am just a ROOKIE in front end development
> > https://user-images.githubusercontent.com/43886292/115244822-ee411980-a0e9-11eb-85c2-d1ef071ed19a.png
> 
> Version 7.1.0 will release a new feature, `annotation`, it can do some event handling.

`annotation` will be a awesome feature to mark events in the graohic , i recommend to be hable to add an annotation based on `timestamp`  and `close, open, high, or low`

**Comment by liihuu** [comment]
Version 7.1.0 has been supported.

**Comment by tumispro** [comment]
Is there any documentation on how to use the `createAnnotation` method to add a text label? Or am I misunderstanding the possibilities?

**Comment by liihuu** [comment]
https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/CustomCandleMarkKLineChart.jsx

**Comment by tumispro** [comment]
Ah thanks. I thought there might be an easier way through the high-level API. 

On another note: thank you for this absolutely amazing library!

**Comment by jakobrosenberg** [comment]
Is there an example of how to create a label for a specific candle? The link above is dead. 🙏

**Comment by liihuu** [comment]
If you are using v9, you need to use `chart.createOverlay({ name: 'simpleTag', points: [{ timestamp, value }] })`.
