### ISSUE TITLE
Where I can get the source of github full sample

### ISSUE THREAD

**Issue by eramax** [liihuu/KLineChart#116]
Hello 

On https://liihuu.github.io/KLineChart/ there is a react sample which I tried to find but didn't success, 
https://github.com/liihuu/KLineChartSample doesn't have this source for the sample on github with all these components on the chart.

Please share with us this sample you have on github.

Kind Regards
Ahmed

**Comment by eramax** [comment]
?

**Comment by liihuu** [comment]
#56
