### ISSUE TITLE
Layer annotations and associated drawExtend above the crosshair cursor

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#117]
Hi, awesome work on the annotation feature, it is exactly what I was looking for. Is it possible to layer the annotations and their popups above the crosshair cursor? Currently when hovering,the crosshair is covering up some of the text. I see that the floating tooltip for the ohlc data is layered above the crosshairs, so I assume it is possible.

**Comment by DeeeeLAN** [comment]
Here is a screenshot of what I am talking about:
![image](https://user-images.githubusercontent.com/12877032/137013067-9f74f3e5-f472-422f-8635-69945b84bae9.png)
The bottom gray box is the annotation, the upper blue box is the associated drawExtend popup. With the crosshair cursor layering on top, it makes it hard to see the text.

**Comment by liihuu** [comment]
I'm thinking of a way to deal with hierarchical issues, do you have any good suggestions?

**Comment by liihuu** [comment]
Yes, but this does not solve the problem completely.
