### ISSUE TITLE
Annotation checkPointInCustomSymbol issue

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#118]
The parameters passed to the function `checkPointInCustomSymbol({ point, coordinate, size })` do not provide enough data to determine if the current cursor location is in the symbol. The `point` passed in is a reference to the annotation point with the timestamp and price, not the current cursor point. All the other annotations have access to that value, but the custom one receives `this._tpPoint` instead, which does not contain x or y coordinates. 

```javascript
      case AnnotationSymbolType.CUSTOM: {
        isOn = this.checkPointInCustomSymbol({
          point: this._tpPoint,
          coordinate: this._symbolCoordinate,
          size
        })
        break
      }
```

I believe swapping `point: this._tpPoint` for `point: point` would fix the issue.

**Comment by liihuu** [comment]
Version 7.2.0 has been fixed.

**Comment by DeeeeLAN** [comment]
This looks good to me. I noticed there seems to be a race condition though, when there are multiple annotations on the chart, mousing over one annotation will cause the popup to flicker as it is checking each annotation for a mouse-over state. It seems you would want to keep those events independent as much as possible.

**Comment by liihuu** [comment]
Maybe it can be implemented in another way, such as clicking and then popping up the window.

**Comment by hbblebc** [comment]
Yeah that is probably a decent workaround for now.

**Comment by DeeeeLAN** [comment]
Yeah that is probably a decent workaround for now.

**Comment by DeeeeLAN** [comment]
Actually it wasn't a race condition, I just had my measurements wrong. The coordinate supplied is the center top of the icon, not the center center. It is definitely working properly.

**Comment by davidPardoC** [comment]
@DeeeeLAN @liihuu  , do you have maybe an example or how to check if the cursos is in the custom point ? 
Im tryng to achieve this way:
`checkPointInCustomSymbol: ({ point, coordinate, size }) => {
              this.kLineChart.subscribeAction('crosshair', (e) => {
                if (coordinate.x <= e.coordinate.x+size && coordinate.x >= e.coordinate.x-size   ) {
                  if(coordinate.y <= e.coordinate.y+size && coordinate.y >= e.coordinate.y-size){
                    return true;
                  }
                }
              });
            },
            drawCustomSymbol: ({ ctx, coordinate, point }) => {
              ctx.save();
              ctx.beginPath();
              ctx.arc(coordinate.x, coordinate.y, 6, 0, 2 * Math.PI);
              ctx.fillStyle = order.orderType === 0 ? '#00CD20' : '#0000ff';
              ctx.fill();
              ctx.strokeStyle = '#ffffff';
              ctx.stroke();
              ctx.save();
              ctx.font = '10px Arial';
              ctx.fillStyle = '#ffffff';
              ctx.fillText('$', coordinate.x - 3, coordinate.y + 3);
            },
            onMouseEnter: (e) => {
              console.log(e);
            },
            onClick:(e)=>{
              console.log(e);
            }`

**Comment by liihuu** [comment]
```js
checkPointInCustomSymbol: ({ mouseCoordinate, coordinate }) => {
    return Math.abs(coordinate.x - mouseCoordinate.x) <= 6
}
```
