### ISSUE TITLE
There is way to set zoom programmatically or reset zoom? 

### ISSUE THREAD

**Issue by davidPardoC** [liihuu/KLineChart#120]
Hi , im very gratefull with the last update with annotations very awesome job, 
I would ask if there is way to set zoom programmatically or reset zoom?

**Comment by liihuu** [comment]
You can use api `setDataSpace`.

**Comment by liihuu** [comment]
Version 7.3.0 adds new zoom api. see [docs](https://github.com/liihuu/KLineChart/blob/master/docs/en/changelog.md).
