### ISSUE TITLE
Additional Documentation needed

### ISSUE THREAD

**Issue by AshwinTayson** [liihuu/KLineChart#125]
Original Title: **Additional Documentation needed for enums in the options**

Hello,

Thank you for this amazing library. The Date, Open, High, Close, Low, Volume labels are not displaying fully in mobile. I see options doc as below.

```
tooltip: {
      showRule: 'always',
      showType: 'standard',
      labels: ['时间', '开', '收', '高', '低', '成交量']
```

What are the possible options for **showRule** and **showType**?
How to break them down appropriately in mobile screen?

**EDIT**: I guess there are multiple doubts. Didnt want to create multiple issues.
How to hide MA in volume?
How to hide additional RSI in RSI indicator?
How to toggle dark/light mode?

I feel the documentation could be bit more detailed. Because you have included so much amazing functionality, it feels like its not configurable.

![image](https://user-images.githubusercontent.com/7329704/118525230-92a39380-b75c-11eb-9325-9cb9c2f75333.png)

**Comment by liihuu** [comment]
Documentation has been updated.

**Comment by AshwinTayson** [comment]
Can u tell about this? I dont want to build a custom indicator for this :)

How to hide additional RSI in RSI indicator? I need only one RSI. And and hide all the MA in volume indicator

**Comment by liihuu** [comment]
The modification of the parameters does not need to be customized.
try it,

`chart.overrideTechnicalIndicator({
     name: 'RSI',
     calcParams: [6]
})`

`chart.overrideTechnicalIndicator({
     name: 'VOL',
     calcParams: []
})`

**Comment by liihuu** [comment]
The modification of the parameters does not need to be customized.
try it,

`chart.overrideTechnicalIndicator({
     name: 'RSI',
     calcParams: [6]
})`

`chart.overrideTechnicalIndicator({
     name: 'VOL',
     calcParams: []
})`
