### ISSUE TITLE
标记位置的稳定性

### ISSUE THREAD

**Issue by lofreer** [liihuu/KLineChart#13]
这应该是一个bug。
研究了下代码，发现作者的Mark标记是根据 xPos 和 price 来定位的，这也意味着，当K线周期切换后（比如5分钟切到4小时 ）， xPos标记就错位失效了。
观察了作者的demo展示，确实存在这么个问题。

**Comment by lofreer** [comment]
X轴的位置标记可以参考tradingview采用时间值

**Comment by liihuu** [comment]
暂时不会更改，即使采用时间值的办法，数据发生变化的时候，已经绘制出来的标记图形位置也会发生变化。
