### ISSUE TITLE
What does the second parameter in SMA represent?

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#131]
As far as I can tell, it appears the second parameter of SMA is used to weight the final price of the period, but that seems to go against the idea of SMA, which should be an equal weight for each price in the period. Am I misinterpreting the formula you use?

**Comment by liihuu** [comment]
You can provide your calculation method.

**Comment by DeeeeLAN** [comment]
Can you provide some more details, or perhaps where you sourced it from? What are the different calculation methods? I am trying to find a good way to describe it to the end user.

**Comment by liihuu** [comment]
Reference Tongdaxin SMA.
I think the best way is to write an SMA according to the user's idea, to replace the original SMA on the chart.

**Comment by DeeeeLAN** [comment]
Thanks, that helps a lot. I might right my own if needed, I will wait and see what people say.
