### ISSUE TITLE
Is it possible for the rect tooltip to stay in the upper left corner? 

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#134]
If not, that would be a nice style option to add.

**Comment by DeeeeLAN** [comment]
Also, when using the 'inside' setting for the y-axis, keep the rect tooltip from overlapping the axis when it is on the same side.

**Comment by liihuu** [comment]
> Also, when using the 'inside' setting for the y-axis, keep the rect tooltip from overlapping the axis when it is on the same side.

`candle.tooltip.rect.offsetLeft` or `candle.tooltip.rect.offsetRight`

**Comment by liihuu** [comment]
> If not, that would be a nice style option to add.

Do you want it to be fixed?

**Comment by DeeeeLAN** [comment]
Yes please. Thanks for the offset suggestion.
