### ISSUE TITLE
[BUG]只能精确到小数点后2位，导致K线显示有问题

### ISSUE THREAD

**Issue by Evi5** [liihuu/KLineChart#135]
如ethbtc的数据
![image](https://user-images.githubusercontent.com/47784329/121485150-8086df00-ca02-11eb-9afa-3a918c25f5a0.png)

**Comment by liihuu** [comment]
有设置精度的api

**Comment by Evi5** [comment]
> 有设置精度的api

setPriceVolumePrecision(6, 6)
可以了，谢谢
![image](https://user-images.githubusercontent.com/47784329/121503993-2e4eb980-ca14-11eb-9628-9e75ec5b336e.png)

**Comment by QGB** [comment]
怎么设置下方时间精确显示到毫秒

**Comment by guxuanye** [comment]
> 怎么设置下方时间精确显示到毫秒

有自定义的API，像这样可以改变显示格式
`

        const chart = init('chart', {
        customApi: {
          formatDate: (dateTimeFormat, timestamp, format, type) => {
            return dayjs(timestamp).format('MM-DD HH:mm:ss');
          },
        }
      });
`
