### ISSUE TITLE
createTag is in docs but not in code 

### ISSUE THREAD

**Issue by davidPardoC** [liihuu/KLineChart#136]
I was reading the docs and in notice that in the instance API there is a method to createTag but it  is not in the library, any info about it ? Another thing there is way to get the actual dataspace?

**Comment by liihuu** [comment]
Which version you use depends on which version of the document. The master is the latest code, but the new features may not have been released.

**Comment by davidPardoC** [comment]
thanks

**Comment by davidPardoC** [comment]
@liihuu  i thinnk, master is not published on npm
