### ISSUE TITLE
What would cause the kLineChart variable to get dereferenced?

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#137]
I have a fairly standard kLineChart instance effect hook set up:
```javascript
  let kLineChart;
  useEffect(() => {
    let data = props.chartData

    cleanData = !('timestamp' in data[0]) ? data.map((d) => {
      return {
        'open': graphAdjusted ? d['adj_open'] : d['open'],
        'high': graphAdjusted ? d['adj_high'] : d['high'],
        'low': graphAdjusted ? d['adj_low'] : d['low'],
        'close': graphAdjusted ? d['adj_close'] : d['close'],
        'volume': graphAdjusted ? d['adj_volume'] : d['volume'],
        'dividend': graphAdjusted ? d['adj_dividend'] : d['dividend'],
        'split': d['split'],
        'timestamp': d['date'].getTime()
      }
    }) : data

    kLineChart = init('momentum-k-line')
    kLineChart.applyNewData(cleanData, true)

    return () => {
      dispose('momentum-k-line')
    }
  }, [props.chartData, props.code, graphAdjusted])
```

In the html, I have a button that is supposed to zoom the chart: 
```javascript
<Button onClick={_ => { kLineChart && kLineChart.zoomAtCoordinate(2.5, null, 300) }} />
```

However, often kLineChart is `undefined` when I press the button, even though the chart loaded fine. That is why I added the `kLineChart &&` to the onClick function. However, obviously then the button doesn't function, but it prevents a page crash at least. 

I noticed your example projects follow this same format, so I assume there is something I need to do to make sure kLineChart doesn't get removed. Any ideas?

**Comment by DeeeeLAN** [comment]
I think it might just be react since it is assigned in the effect hook. I stored the reference to a state variable and referenced it that way and it appears to be working fine now. Not sure if it would make more sense to use a ref though. Any thoughts?

**Comment by liihuu** [comment]
You may need to learn more about react hooks.

**Comment by DeeeeLAN** [comment]
I am figuring it out little by little. I tried following the model you provided in the examples.
