### ISSUE TITLE
getConvertPictureUrl() with sub-indicators present is not laying out properly

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#138]
I call `window.open(kLineChart.getConvertPictureUrl())` when the button is pressed. It creates the following image. Normally, the two sub-indicators fill the empty space at the bottom. 

![image](https://user-images.githubusercontent.com/12877032/121765463-d7261300-caff-11eb-9d81-3e9f94a30457.png)

**Comment by liihuu** [comment]
This is my newly created bug. 🙁

**Comment by liihuu** [comment]
Try version 7.5.0

**Comment by DeeeeLAN** [comment]
7.5.0 fixes the layout, but now the screenshot is ignoring my styling and loads the default styles. Additionally, if I add any graphic marks, they don't show up in the screenshot. Sorry it took me some time to test this.
