### ISSUE TITLE
想设置单根k线的颜色，能不能加一个设置某一根k线颜色的属性

### ISSUE THREAD

**Issue by tangjiemian** [liihuu/KLineChart#14]
{ open: 141.77, high: 170.39, low: 120.25, close: 145.72 ,color:#555}

**Comment by liihuu** [comment]
是什么样的需求，需要设置单根蜡烛柱的样式？

**Comment by tangjiemian** [comment]
这样可以做一些定制化的指标功能。趋势指标中，是会把阳线看成是阴线。阴线看成是阳线。其实就是改变k线的颜色

**Comment by liihuu** [comment]
如果紧急，可以fork后，尝试自己修改。
