### ISSUE TITLE
How to add text in background

### ISSUE THREAD

**Issue by itxtoledo** [liihuu/KLineChart#140]
How do i put my logo like this binance chart 
![image](https://user-images.githubusercontent.com/21026675/121789194-4eb07c80-cbaa-11eb-926e-50f18f0dbf92.png)

**Comment by danielmalencar** [comment]
CSS background image on chart div or img element inside chart div.

**Comment by itxtoledo** [comment]
> CSS background image on chart div or img element inside chart div.

Thanks bro! I solved this with this snippet using styled-components

```JavaScript
const TVChartContainer = styled.div`
  width: 100%;
  height: calc(100% - 40px);
  background-color: #ffffff;
  display: flex;
  color: #000000;
  position: relative;

  ::before {
    content: "";
    position: absolute;
    top: 0px;
    right: 0px;
    bottom: 0px;
    left: 0px;
    background-image: url(/main_logo.png);
    background-size: 192px 50px;
    background-position: center;
    background-repeat: no-repeat;
    filter: grayscale(100%);
    opacity: 0.2;
  }
`;
```

![image](https://user-images.githubusercontent.com/21026675/121817746-917d5d80-cc59-11eb-98d0-fdacec5e29b4.png)
