### ISSUE TITLE
Is it posible to find fixel with converToPixel() outside xdataindex or ydataindex?

### ISSUE THREAD

**Issue by davidPardoC** [liihuu/KLineChart#143]
I was trying to create annotatios in custom places along xaxis and y axis based on timestamp and price , but when i want to covert timestamp to pixel with  convertToPixel() it  only gives me the pixel that is in the center of the candle

**Comment by liihuu** [comment]
The next version of the `tag` may be what you want.

**Comment by davidPardoC** [comment]
I was warking with create tag but is not what i was looking for, I  use create Anotation to draw buy or sell events , and im using the type of Custom so i can dray a custom Shape  with shadows , and onother good looking stuff, this is how mi code looks.
Note: `order ` is an object comming from websockets, it has this strucutre `{timesTamp:number, openPrice:number} `, this openPrice is comming already calculated to be placen on ask or bid value , depending of operation type (buy, sell)
`const lastCandle=
            this.kLineChart.getDataList()[
              this.kLineChart.getDataList().length - 1
            ];

          this.kLineChart.createAnnotation({
            point: { timestamp: lastCandle.timestamp, price: lastCandle.close },
            styles: {
              symbol: {
                position: 'point',
                type: 'custom',
                offset: [0, 0],
              },
            },
            drawCustomSymbol: ({ ctx, coordinate }) => {
              const pxPoint: any = this.kLineChart.convertToPixel(
                {
                   xAxisValue: order.timesTamp,
                   yAxisValue: order.openPrice,
                },
                {}
              );
              ctx.beginPath();
              ctx.shadowColor = 'black';
              ctx.shadowBlur = 10;
              ctx.shadowOffsetX = 0;
              ctx.shadowOffsetY = 0;
              ctx.arc(pxPoint.x, pxPoint.y, 8, 0, 2 * Math.PI);
              (ctx.fillStyle = order.orderType === 0 ? '#00CD20' : '#0000ff'),
                ctx.fill();
              ctx.strokeStyle = 'white';
              ctx.stroke();
              ctx.fillStyle = 'white';
              ctx.fillText(
                order.orderType === 0 ? 'B' : 'S',
                coordinate.x - 3,
                pxPoint.y + 3
              );
            },
          });`
So i think i realize that somethings points ar not showing because the convertToPixel(), because it cant find the openPrice that is coming fomr te socket iniside de dataset in the chart, same with timestamp, somethibg this timestamp is not in the array of data so it is unable to find the right pixel.
Please let me know if you need more explanation

**Comment by liihuu** [comment]
When receiving data from websocket, do this,
```js
// order is the data pushed by websocket.
const { timestamp, openPrice } = order;
this.kLineChart.createAnnotation({
  point: { timestamp, price: openPrice },
  styles: {
    symbol: {
      position: 'point',
      type: 'custom',
      offset: [0, 3],
    },
  },
  drawCustomSymbol: ({ ctx, coordinate }) => {
    ctx.save();
    ctx.beginPath();
    ctx.shadowColor = 'black';
    ctx.shadowBlur = 10;
    ctx.shadowOffsetX = 0;
    ctx.shadowOffsetY = 0;
    ctx.arc(coordinate.x, coordinate.y, 8, 0, 2 * Math.PI);
    ctx.fillStyle = order.orderType === 0 ? '#00CD20' : '#0000ff';
    ctx.fill();
    ctx.strokeStyle = 'white';
    ctx.stroke();
    ctx.fillStyle = 'white';
    ctx.textBaseline = 'middle';
    ctx.textAlign = 'center';
    ctx.fillText(order.orderType === 0 ? 'B' : 'S', coordinate.x, coordinate.y);
    ctx.restore();
  }
});
```

**Comment by davidPardoC** [comment]
Still not working because timestamp and openPrice (but there are closer values) coming from sockets are not  in the dataset and I  was looking inside the code and all the methods that u use to find the position for an annotation are based in the points that are already in the chart, thats why i was asking if its there are way to use covertToPixel() with values outside the data array .

**Comment by liihuu** [comment]
`convertToPixel(value, finder)` 
By default, it will go to the data set to configure the position closest to the timestamp.

**Comment by davidPardoC** [comment]
Yes, i realize that when i saw nearBinarySearch method, hop next releae supports absolute xAxis convert to pixel. Thanks.
Awesome Job by the way
