### ISSUE TITLE
可否放出示例https://liihuu.github.io/KLineChart的源码

### ISSUE THREAD

**Issue by iamweilee** [liihuu/KLineChart#15]
如题所问

**Comment by liihuu** [comment]
https://liihuu.github.io/KLineChart  只是基于插件做的静态页面，并无太大的参考意义。你可以参考https://github.com/liihuu/KLineChartSample  这个里面包含了对插件做单个功能拆分的基于主流前端框架的示例代码。

**Comment by iamweilee** [comment]
想组装一个像https://liihuu.github.io/KLineChart的完整的页面  想偷懒用大佬的代码
示例https://github.com/liihuu/KLineChartSample过于零碎  组装出https://liihuu.github.io/KLineChart的页面 还是需要花点时间的

**Comment by iamweilee** [comment]
通过sourcemap还是被我给抓下来了：） 感谢你的付出

**Comment by TomorrowLsn** [comment]
> 通过sourcemap还是被我给抓下来了：）感谢你的付出

欢迎加入本插件的交流群677936660
