### ISSUE TITLE
Chart Zoom and Focus Position? 

### ISSUE THREAD

**Issue by tanolan** [liihuu/KLineChart#154]
Hello, sorry if there is documentation on this but I was searching and couldn't find it.  I have two questions related to zoom and focusing on a candle position: 

1. Zoom - I notice that when I keep zooming out, I will get to a limit.  The feature list below says that a Zoom Ratio can be set, can I set this to allow for the chart to be zoomed out more than the default setting? If so, how do I set this?
2. Candle Focus - I would like to be able to set the focus (horizontal scroll position) to a particular candle, how do I do this? 

https://github.com/liihuu/KLineChart/blob/master/docs/en/features.md
![image](https://user-images.githubusercontent.com/8295183/129484465-3b3dc663-3454-4541-9d98-154f8c5d3d90.png)

Thank you for the help,
Tim

**Comment by davidPardoC** [comment]
1. May this culd hel with the zoom [setDataspace()](https://github.com/liihuu/KLineChart/blob/dev/docs/en/instance-api.md#setdataspacespace)
2. With this methods you can scroll or zoom to a candle index  [zoomAtDataIndex](https://github.com/liihuu/KLineChart/blob/dev/docs/en/instance-api.md#zoomatdataindexscale-dataindex-animationduration) and [scrollToDataIndex](https://github.com/liihuu/KLineChart/blob/dev/docs/en/instance-api.md#scrolltodataindexdataindex-animationduration)

**Comment by tanolan** [comment]
Thank you @davidPardoC!
