### ISSUE TITLE
zoomAtPosition - how to use properly?

### ISSUE THREAD

**Issue by tanolan** [liihuu/KLineChart#155]
Hello, I have some questions about the zoomAtPosition function: 

1. Scale - what scale should I set to zoom all the way out (as in I want the same effect as using the mouse wheel to zoom all the way out)? 
2. Position - I'm assuming position sets the let most candle index? When I set the position, I don't see any change.  If the chart is displaying 500 candles, how do I set the position to 200 (so that the user is at the 200th candle, but can still scroll left if they want)? 

Thank you for the help,
Tim

**Comment by liihuu** [comment]
Position,  is the position at which the data index is scaled.
