### ISSUE TITLE
applyMoreData 的数据是反的？

### ISSUE THREAD

**Issue by dazhoudotnet** [liihuu/KLineChart#157]
看来是只考虑到了向前的情况，并没有考虑到向后批量添加的情况。

正常加载，是旧数据在前，新数据在后。

applyMoreData 的时候，需要 反过来？

**Comment by liihuu** [comment]
更新用update

**Comment by dazhoudotnet** [comment]
> 更新用update

对的.但是udpate只支持单item不支持array.

另外请问,已知有: Timestamp ,Price .怎么样让图滚动到对应的点?

**Comment by liihuu** [comment]
有滚动的api
