### ISSUE TITLE
😟 klinecharts error: The chart cannot be initialized correctly. Please check the parameters. The chart container cannot be null and child elements need to be added!!!

### ISSUE THREAD

**Issue by feng005211** [liihuu/KLineChart#158]
😟 klinecharts error: The chart cannot be initialized correctly. Please check the parameters. The chart container cannot be null and child elements need to be added!!!

环境
"klinecharts": "^7.5.0"
"vue": "^2.6.10",
"vuex": "^3.1.1",

**Comment by feng005211** [comment]
代码
      <div id="chart-k-line" class="k-line-chart" />


// 全量引入，包含所有内置的技术指标和绘图标记
import { init } from 'klinecharts'

mounted：
 this.kLineChart = init('chart-k-line')

**Comment by liihuu** [comment]
请确保容器dom加载进来后再初始化图表。

**Comment by ch-m-n** [comment]
> @liihuu I'm trying to init multiple charts with different id tag, but have a same error for other two ![Screen Shot 2021-10-14 at 3 20 23 PM](https://user-images.githubusercontent.com/1939783/137389758-7c89cdeb-807b-4499-b483-40f32b9dcc6d.png) ![Screen Shot 2021-10-14 at 3 20 27 PM](https://user-images.githubusercontent.com/1939783/137389762-c91d9b81-3a74-4230-b748-cf1bb86869c6.png) ![Screen Shot 2021-10-14 at 3 21 17 PM](https://user-images.githubusercontent.com/1939783/137389764-072bc2bf-0751-4ec3-a1bd-7bd8e7236300.png) Can you suggest why ?

I got the same problem. Do you know how to solve it?
