### ISSUE TITLE
Show seconds on x-axis?

### ISSUE THREAD

**Issue by davidPardoC** [liihuu/KLineChart#159]
Hi, there is a way to show time with seconds un x-axis or it has to be donde in the source code of the library?

**Comment by davidPardoC** [comment]
I solve it of by adding `second:'2-digit'`, on `TimeScaleStore` class
`this._dateTimeFormat = new Intl.DateTimeFormat(
      'en', {
        hour12: false, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second:'2-digit'
      }
    )`

**Comment by liihuu** [comment]
V9 supported.
