### ISSUE TITLE
缩放K线时画线工具画出的线段不能实时跟随缩放，出现延迟渲染现象

### ISSUE THREAD

**Issue by iamweilee** [liihuu/KLineChart#16]
如题，如gif图所示：
![VID_20200424_123850](https://user-images.githubusercontent.com/1096160/80175793-3e95b080-8629-11ea-9ecd-fab0b3035cad.gif)

**Comment by liihuu** [comment]
https://github.com/liihuu/KLineChart/issues/12#event-3248728433

待新版本发布

**Comment by iamweilee** [comment]
3q
