### ISSUE TITLE
Draw custom overlay

### ISSUE THREAD

**Issue by Julien-R44** [liihuu/KLineChart#167]
Hello,
Tags and annotations are good features for simple uses, but in more advanced cases, it is not possible to achieve what you want with only theses two "primitives"/"overlays".

In my case I would have liked to be able to add on my chart the orders and positions of my Binance account in real time, and to be able to drag and drop them to update them. This is an example of use a little more advanced that it is not possible (I think) to achieve using the current exposed api.

What I would like to do is to add an `overlayStore` in `ChartData`, and to propose an api a bit similar to the tags/annotations api: 

```
klineChart.addOverlay({
 id: "position_and_orders",
 name: "PositionAndOrders",
 draw: (ctx, xAxis, yAxis) => {
   // draw what we want with ctx stuff and xAxis, yAxis mainly for using convertToPixel etc
 }
})
```

And then, just draw the user custom overlays in `CandleView` ( or another view file, I'm still not sure how the whole thing is structured ) : 
```
_drawOverlays () {
  this._chartData.overlayStore().get(this._paneId).forEach(overlay => {
   overlay.draw(this._ctx, this._viewport)
  })
}
```

With this API, it would be possible for the user to draw anything he wants on his chart 

I implemented this in the [most naive way in my fork](https://github.com/liihuu/KLineChart/compare/master...Genius-Station:custom-overlays?expand=1), but is it something you think is interesting for the library? Is there a better solution? If you have any remarks, please tell me, I'll adapt my implementation and propose you a nice pull request asap. I would love to contribute to this project 😊

**Comment by mawsyh** [comment]
any updates on this ?
