### ISSUE TITLE
y-axis not scaling

### ISSUE THREAD

**Issue by DanielMartini** [liihuu/KLineChart#172]
Hi!

I think there's a problem drawing very small values, even I set the precision with `setPriceVolumePrecision(7, 7)`,  the y-axis "gaps" goes 0.01 by 0.01 and the value of asset is much lower, maybe I'm missing something?

this is the chart of QTUM/BTC

![image](https://user-images.githubusercontent.com/8677856/140178023-6e432750-0a70-46db-8d1f-13c1e01c443e.png)

Thanks!

**Comment by liihuu** [comment]
Which version?

**Comment by tquangfx** [comment]
Do you have any indicator on the chart ? 
If you have any, you might have to config the indicator precisions too
