### ISSUE TITLE
鼠标拖动bug

### ISSUE THREAD

**Issue by wolb1211** [liihuu/KLineChart#176]
![image](https://user-images.githubusercontent.com/48630957/145558352-e1220f60-4239-48eb-93d3-34f8f849aa28.png)
![image](https://user-images.githubusercontent.com/48630957/145558411-1996f819-fdfa-4366-ae9c-a5e33eb34c41.png)
 鼠标在价格轴上按住拖动到k线里，出现显示bug。如果先在k线中使用过拖动，没有这种情况

**Comment by liihuu** [comment]
v8.1.1 已修复。

**Comment by idbeny** [comment]
切换品类时还是会出现这样的问题。
比如，在USDJPY拖动价格线，再从USDJPY切到USDCHF。
