### ISSUE TITLE
多幅K线图 拖动上面K线的VOL指标分割线会超出当前K线区域覆盖到下面K线中

### ISSUE THREAD

**Issue by iamweilee** [liihuu/KLineChart#18]
如题如图
![1](https://user-images.githubusercontent.com/1096160/80183532-92a99080-863b-11ea-9912-13c56db93094.png)

**Comment by iamweilee** [comment]
![1](https://user-images.githubusercontent.com/1096160/80183578-aa811480-863b-11ea-9fad-fb5743773f13.png)

**Comment by liihuu** [comment]
V5.2.0解决了该问题
