### ISSUE TITLE
Technical indicator line color is not overridden

### ISSUE THREAD

**Issue by aka-swork** [liihuu/KLineChart#183]
Example of the code is taken from the technical-indicator.html

```js
...
chart.createTechnicalIndicator({ name: 'VOL', calcParams: [10], styles: { margin: { top: 0.2, bottom: 2 },
    line: {
      size: 2,
      colors: ['#009600']
    },
} })
...
```
<img width="1029" alt="Screenshot 2022-01-14 at 14 27 06" src="https://user-images.githubusercontent.com/15668549/149523719-e2534793-339e-418c-81c4-69d88957d887.png">

On the screenshot bellow the size of the line is overridden, but the color is the default one https://github.com/liihuu/KLineChart/blob/master/docs/en/styles.md

```js
...
line: {
      size: 1,
      colors: ['#FF9600', '#9D65C9', '#2196F3', '#E11D74', '#01C5C4']
    },
...
```

<img width="1024" alt="Screenshot 2022-01-14 at 14 27 48" src="https://user-images.githubusercontent.com/15668549/149523736-81d7b182-2bbf-43b9-83b4-2cc5c2244ffd.png">

**Comment by liihuu** [comment]
Version 8.3.0 fixed it.

**Comment by liihuu** [comment]
Version 8.3.0 fixed it.
