### ISSUE TITLE
Is it possible to display the chart in full in the full size of the chart? 

### ISSUE THREAD

**Issue by majid1605** [liihuu/KLineChart#188]
My chart is as follows:
![22222222](https://user-images.githubusercontent.com/3286889/149976216-6a8d561c-4dd1-4870-b6f1-a6147a5b5575.png)

Is it possible to display the chart in full in the full size of the chart?
Like the image below:
![11111](https://user-images.githubusercontent.com/3286889/149976267-6dff2357-847b-4fe2-a705-717caf46143e.png)

**Comment by liihuu** [comment]
`setDataSpace`
