### ISSUE TITLE
Is crosshair labels customizable?

### ISSUE THREAD

**Issue by fuzzthink** [liihuu/KLineChart#192]
I want to customize both labels on the crosshair, eg:

y-label: "$3.55 (n%)"
where n% is +- % from last price

x-label: "2021-11-11 (5.2 mo. ago)"
where "mo" can be "days", "weeks", "years" on daily bars, and shorter time frames in intraday.

If it's possible, please show how it can be done. If not, please consider adding.

thank you!

**Comment by fuzzthink** [comment]
One more crosshair request - please allow crosshair label to show future dates. Eg. if I'm on Daily chart, and crosshair is 13 bars in the future, please allow the date to be shown, weekends adjusted.

**Comment by liihuu** [comment]
There is not much time to do this feature for now. If you need this feature very much, you can maintain a branch yourself.

**Comment by fuzzthink** [comment]
Got it. Will close and open a discussion for others to comment
