### ISSUE TITLE
ipad或者移动端模式下

### ISSUE THREAD

**Issue by flameOnYou** [liihuu/KLineChart#196]
在ipad模式下，点击绘制自定义图表，createShapeDataSource的param.points数组 为空。在pc端不会
![image](https://user-images.githubusercontent.com/20795930/152960020-0359268a-700c-449f-8734-93d59f008687.png)

**Comment by liihuu** [comment]
没有针对设备做特殊的逻辑，这种情况理论上应该不存在，需要验证一下。

**Comment by liihuu** [comment]
v8.3.6 已修复该问题
