### ISSUE TITLE
可否添加配置项可去掉右侧的均线价格

### ISSUE THREAD

**Issue by iamweilee** [liihuu/KLineChart#20]

**Comment by iamweilee** [comment]
![3](https://user-images.githubusercontent.com/1096160/80196243-b37be100-864f-11ea-920a-41bcb72a8a18.png)

**Comment by iamweilee** [comment]
包括所有指标的均价

**Comment by iamweilee** [comment]
包括所有指标的均值

**Comment by liihuu** [comment]
当前版本5.1.1没有此项功能，该功能是下一个版的新增配置。这个不是指标均值，是技术指标的最好一条数据值。
