### ISSUE TITLE
confusing date format on daily bars + local timezone

### ISSUE THREAD

**Issue by ovresko** [liihuu/KLineChart#204]
confusing date format on daily bars + local timezone
if timezone EST daily bars are shwing day-1 19:00:00 that's expected since  timestamp at hour 00 to utc - offset may shift by 1 day,
users get confused.
it should format as yyyy-mm-dd for daily and yyyy-mm-dd hh:mm for intraday

**Comment by ovresko** [comment]
i did dig a little and found this function but the part where regex ==24 is not clear
 it's looking for when a day ==24 since dateTimeStringArray[1] is the day part of date
can anyone explain 

export function formatDate (dateTimeFormat, timestamp, format = 'MM-DD hh:mm') {
  if (isNumber(timestamp)) {
    const dateTimeString = dateTimeFormat.format(new Date(timestamp))
    const dateTimeStringArray = dateTimeString.split(', ')
    const dateStringArray = dateTimeStringArray[0].split('/')
    const date = {
      YYYY: dateStringArray[2],
      MM: dateStringArray[0],
      DD: dateStringArray[1],
  ==>    'hh:mm': dateTimeStringArray[1].match(/^[\d]{2}/)[0] === '24'
        ? dateTimeStringArray[1].replace(/^[\d]{2}/, '00')
        : dateTimeStringArray[1]
    }
    return format.replace(/YYYY|MM|DD|(hh:mm)/g, key => date[key])
  }
  return '--'
}

**Comment by ovresko** [comment]
anyone facing same problem, a workaround is possible
just check before if you're displaying daily add offset to timestamp
let daily = timeframe.includes("d")
let offset = 0
if(daily){
  offset = new Date().getTimezoneOffset()*60000
}
....
{
              'timestamp':  o[index][0]+offset ,
              'open': o[index][1],
              'close': c[index][1],
              'low': l[index][1],
              'high': h[index][1],
              'volume': v[index][1]
            }

**Comment by liihuu** [comment]
Setting the timezone might be what you want.
