### ISSUE TITLE
Is it possible to change plots title for default indicators

### ISSUE THREAD

**Issue by phamhungvn** [liihuu/KLineChart#205]
i.e: The default `regeneratePlots` function for `MA` is:
```Javascript
regeneratePlots: (params) => {
    return params.map(p => {
        return { key: `ma${p}`, title: `MA${p}: `, type: 'line' }
    })
}
```

I want to change the `title` as below, adding `()` around params in the `title`
```Javascript
regeneratePlots: (params) => {
    return params.map(p => {
        return { key: `ma${p}`, title: `MA(${p}): `, type: 'line' }
    })
}
```

Is there a way for overriding the plots title without creating another custom indicator template?

-----
This customization is also useful in case for other indicators.
i.e: the `RSI` display tooltips as
```
RSI(6, 12, 24)   RSI2:   RSI2:   RSI3:
```
If setting options for hiding name & params, then the plot doesn't clear
```
RSI2:   RSI2:   RSI3:
```

**Comment by liihuu** [comment]
You can only customize templates for now.
