### ISSUE TITLE
Adding button for jump to realtime bar

### ISSUE THREAD

**Issue by phamhungvn** [liihuu/KLineChart#206]
Does the lib have built-in feature to add button for jump to real-time bar like the button in the Binance app? Or is there a way to do it?
| Desc | Photo on the Binance app |
| --- | --- |
| The real-time bar doesn't touch the `yAxis` | ![image](https://user-images.githubusercontent.com/85485496/155855647-4dc4b728-314e-4067-8ec8-e90222e99164.png) |
| The real-time bar is over the `yAxis` | ![image](https://user-images.githubusercontent.com/85485496/155855648-04a2e7fb-c002-4052-8c07-5645b671bbc5.png) |

**Comment by liihuu** [comment]
Special features, no development plan for the time being.

**Comment by QGB** [comment]
how to jump to specific time ? @liihuu
