### ISSUE TITLE
仍然是图层位置的不确定性

### ISSUE THREAD

**Issue by lofreer** [liihuu/KLineChart#21]
感谢作者，又做了大量的更新。

但，把datalist的索引值用作xPos，问题真的有点大。

譬如：
需要将图层绘制数据存入数据库，当数据取出套用时，若datalist长度发生了变化，这不就等同于刻舟求剑了吗，实际上随着时间的变化datalist的长度一直在变化。
纵轴的判断值为price，为什么横轴的判断值就设为了datalist的索引值了呢，因为它不是确定值，不知道作者是基于什么考虑，有些想不明白。
这个问题的存在，意味着，这个K线图只是好看，实用性一般。因为没办法针对数据去做分析处理，然后在K线图中直接表现，而是要把数据植入到图表中再取中，跟据不稳定的datalist索引值去做分析计算，然后再次进行图形绘制。

当然，整年项目的零依赖真的很赞，感谢作者的实现。

**Comment by iamweilee** [comment]
> 需要将图层绘制数据存入数据库，当数据取出套用时，若datalist长度发生了变化，这不就等同于刻舟求剑了吗，实际上随着时间的变化datalist的长度一直在变化。

没看懂这跟图表有什么关系 有什么影响

**Comment by lofreer** [comment]
> 没看懂这跟图表有什么关系 有什么影响
保存当前蜡烛图的索引值到数据库，有什么意义呢，再取出来复用时，索引值还是那个索引值吗

**Comment by lofreer** [comment]
> 没看懂这跟图表有什么关系 有什么影响

保存当前蜡烛图的索引值到数据库，有什么意义呢，再取出来复用时，索引值还是那个索引值吗

**Comment by lofreer** [comment]
@liihuu 类似于#22issue的问题，只不过我展开的更详细
