### ISSUE TITLE
想請教 Demo 頁面的 Data loading 畫面是怎麼處理的？

### ISSUE THREAD

**Issue by HKChen** [liihuu/KLineChart#211]
想請教 Demo 頁面的 Data loading 畫面是怎麼處理的？
利用 css 去  override 在圖層的上面嗎謝謝您

**Comment by liihuu** [comment]
做一个loading   覆盖在容器上面

**Comment by HKChen** [comment]
@liihuu Thanks It's Work
![Screen Shot 2022-03-14 at 3 40 15 PM](https://user-images.githubusercontent.com/4105970/158126280-394bff8b-1459-46ff-82e8-b14fb7035730.png)
