### ISSUE TITLE
Draw chart from the right side

### ISSUE THREAD

**Issue by hanna-zn** [liihuu/KLineChart#213]
Hi everyone, 
I've investigated documentation, but did't find a way how to draw something like these charts.
I know that question more for stackoverflow, but I believe community here can help me

<img width="381" alt="Screen Shot 2022-03-17 at 22 28 04" src="https://user-images.githubusercontent.com/101482506/158898076-7193fed5-4b95-4c07-b473-d91e68099ae5.png">

**Comment by liihuu** [comment]
It can be drawn externally and then add the drawn dom to the chart through `createHtml`.
