### ISSUE TITLE
Code for the sample chart: https://klinecharts.com/sample

### ISSUE THREAD

**Issue by MrKampla** [liihuu/KLineChart#214]
Hi,
I cannot find a full source code of the sample chart that is presented here: https://klinecharts.com/sample

I'm particularly interested in the tool list on the left-hand side and the top belt, where You can select candle interval and take a screenshot.
I've marked the areas that interest me in the screenshot below:
<img width="1713" alt="Screenshot 2022-03-18 at 20 02 35" src="https://user-images.githubusercontent.com/46401284/159068264-6ced2c3d-5ea8-4ece-a828-2c82be5a094f.png">

How can I access the code for this site?

**Comment by MrKampla** [comment]
I'm aware of response that have been given here: #56, but I don't understand why You don't want to share the code for the site. In my opinion, it would be valuable to see the implementation of this. I'm working in React and this would save me a ton of time.

**Comment by dayatang** [comment]
I have the same question.

**Comment by rockliuxn** [comment]
Please share the source code of the sample page, the toolbar above is very useful, thank you!

**Comment by yujiantao4616** [comment]
please, the samlpe page is comprehensive, the code would be helpful to learn the Api

**Comment by yangar** [comment]
yes please the source code or more samples. How to implement the time series ?

**Comment by liihuu** [comment]
Will not be public in a short time.

**Comment by QinYongKang** [comment]
短时间内？可现在都2023年3月了呀，哥 ～
