### ISSUE TITLE
Is update graphic in real time with 1Day, 1 Week, 1Mont ?

### ISSUE THREAD

**Issue by andreamc0003** [liihuu/KLineChart#221]
Hi! 
Please help me, regarding the chart periods for creating 1DAY, 1 WEEK, 1MONTH candlesticks. 
It happens that I am using your library and I want to present the candles with the consumption of data through websockets and only in these periods in the graph can not be observed the current value of the **close** property of the object that I am adding when I use the method:  **' kLineChart?.updateData()'.**

Is it possible to do it another way?

**Comment by liihuu** [comment]
The timestamp can determine whether the current is closed.
