### ISSUE TITLE
Volume of bar when price values is too small?

### ISSUE THREAD

**Issue by zeeshan-shabbir** [liihuu/KLineChart#223]
I am using this graph to show historic data that has value like this.
   `{
        timestamp: 164932074000,
        open: 1.0885,
        high: 1.08853,
        low: 1.08837,
        close: 1.08846,
    },`
the values is small bar is not taking volume I used   volume: 1200, not worked.
![Screenshot (13)](https://user-images.githubusercontent.com/80969033/162348971-8444e6d4-28e5-4f73-b093-82ae9757d852.png)

i want to increase the height i:e volume of bar.

**Comment by liihuu** [comment]
https://klinecharts.com/guide/faq#the-candle-shows-a-line-no-fluctuation-what-to-do

**Comment by zeeshan-shabbir** [comment]
thanks . I was searching many thinks but did not find  thats why i am asking here.


I want to known can we add future points in graph just time with no values and then update? is it possible

**Comment by zeeshan-shabbir** [comment]
> https://klinecharts.com/guide/faq#the-candle-shows-a-line-no-fluctuation-what-to-do

thanks
