### ISSUE TITLE
Why is RSI indicator value different than RSI value on other platforms?

### ISSUE THREAD

**Issue by zetzetto** [liihuu/KLineChart#225]
I was checking the RSI value and noticed that when RSI is 80 on KlineChart it was 77 on tradingview, same data and same period (14 days). I guess the calculation method maybe different. I know it's not a issue but has anyone tried to match the RSI to the tradingview RSI value?

**Comment by liihuu** [comment]
If you know the Tradingview calculation method, I recommend customizing RSI to override.

**Comment by Inblac** [comment]
tradingview RSI indicator using rma(14) to caculate avgGain avgLoss
this may be the reason
