### ISSUE TITLE
在拖动时蜡烛柱会突然变得很长，超出屏幕范围

### ISSUE THREAD

**Issue by yangfancn** [liihuu/KLineChart#231]
![动画](https://user-images.githubusercontent.com/42950770/165454059-20af0876-33fd-4d5c-8b24-293f126b3617.gif)
是我哪里没配置好吗？

**Comment by liihuu** [comment]
贴一下配置，给一份数据

**Comment by yangfancn** [comment]
> 贴一下配置，给一份数据
数据：
[https://github.com/liihuu/KLineChart/issues/231#issuecomment-1110594951](https://github.com/liihuu/KLineChart/issues/231#issuecomment-1110594951)
配置
`
const chart = init(document.querySelector('#chart'), {
        candle: {
            margin: {
                top: .3,
                bottom: .3
            },
        }
    });
chart.applyNewData(data);
`

**Comment by liihuu** [comment]
数据存在一些问题，开低高收里面，有的最高并不是最高，最低也不是最低。
