### ISSUE TITLE
是否有办法实现自定义数据传入calcTechnicalIndicator？

### ISSUE THREAD

**Issue by BaoBaoJiu** [liihuu/KLineChart#233]
KLineData是小时数据，传到calcTechnicalIndicator里的就是小时数据。
如果计算指标的时候还想用到分钟数据，则需要在calcTechnicalIndicator中直接调用KLineChart封装外的全局数据。但这里就出现强耦合了，导致每个不同的Chart实例都必须单独写不同的cb处理代码。

**Comment by liihuu** [comment]
后续考虑添加进去

**Comment by liihuu** [comment]
v8.6.0 添加了属性`extendData`

**Comment by yetrun** [comment]
> v8.6.0 添加了属性`extendData`

新添加的 extendData 的在 overrideTechnicalIndicator 方法里没有被声明为可选的，这与文档介绍的不符。

另外，可在这里介绍下 extendData 的用处是什么吗？文档中仅提到是“拓展数据”，不明白是何意思。
