### ISSUE TITLE
Something in commit c32e6fc92 is causing the sub-indicators to not cause the main chart to resize

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#238]
I am using flex to layout the graph and all the other stuff I have assoicated with it. Previously, on 8.2.0 and before, it looked like this:
![image](https://user-images.githubusercontent.com/12877032/167740563-5a93740c-9b29-4237-a81b-1cc81ef6a4c8.png)

After updating to 8.3.0, it now looks like this:
![image](https://user-images.githubusercontent.com/12877032/167740401-d16e8cc7-ea9d-4ef4-85e2-c0ba8d850ddb.png)

If I turn off the sub-indicators, it is easy to see that the size of the main graph is the same as the size of the entire graph in the old image, and everything fits in the box nicely. For some reason, when adding the sub-indicators, the main graph is no longer resizing to fit everything in the size of the container.

**Comment by DeeeeLAN** [comment]
Specifically, I have narrowed it down to a change made in commit c32e6fc92.

**Comment by liihuu** [comment]
Let me check it.

**Comment by jinusean** [comment]
I was having the same issue regardless of sub-indicators. 
I had to add `min-width: 0` to  the container element and all effected ancestor elements. 
Here is the relevant stackoverflow [post](https://stackoverflow.com/a/66689926).
