### ISSUE TITLE
如何在主图上创建一个矩形框呢

### ISSUE THREAD

**Issue by mick-sun** [liihuu/KLineChart#243]
通过chart.createShape配置styles中的polygon在图上只有一个线段，请问这个api具体该如何使用，谢谢

**Comment by figozhu** [comment]
createShape画4条segment

**Comment by liihuu** [comment]
可以自定义一个矩形模板
示例：https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/DrawShapeKLineChart.jsx
