### ISSUE TITLE
Draggable Tags

### ISSUE THREAD

**Issue by olablt** [liihuu/KLineChart#251]
Hello,

is there a code snippet to modify the tag and make it draggable vertically?

like in this example https://jsfiddle.net/randalhsu/5un8r93g/

**Comment by XYUU** [comment]
This function may be supported in the next version. I made a similar function, but through the price line.

**Comment by olablt** [comment]
> This function may be supported in the next version. I made a similar function, but through the price line.

can you share the code?

**Comment by XYUU** [comment]
> 
`
const shape= {
name: "priceLine",
lock: false,
mode: "weak_magnet"
}
chart.createShape(shape, "candle_pane")
`

**Comment by olablt** [comment]
> > 
> 
> `const shape= { name: "priceLine", lock: false, mode: "weak_magnet" } chart.createShape(shape, "candle_pane")`

is it possible to restrict the dragging to vertical only?

**Comment by liihuu** [comment]
V9 supported.
