### ISSUE TITLE
在滚动放大和缩小的时候priceLine的value会发生改变

### ISSUE THREAD

**Issue by XYUU** [liihuu/KLineChart#253]
就是我本身没有拖动线，只是放大或缩小图表，值会随之改变。
![(X@QA@DV~IO~ZM85P ~1JW6](https://user-images.githubusercontent.com/9715021/174553716-09e5a48a-a16d-40cf-94ec-3f5c4319d169.png)
![PLFME%HUHQ5ND5RTC86L60M](https://user-images.githubusercontent.com/9715021/174553732-bce47c0a-5e3d-47f8-af56-ca5f9de4ebe4.png)
我认为坐标可以不那么精确，而值一定要非常精确，毕竟人肉眼看不出坐标的差异，但值这个很关键。
我刚刚测试了一下，官方的示例也有这个问题，可能是我屏幕比较大导致的？我是4K屏。

我认为就是这个地方，画的时候根据位置算值没问题，画完之后，应该是反过来，根据值去算坐标位置。

**Comment by liihuu** [comment]
`priceLine`画线模型的问题，可以先自定义一个覆盖掉内置的

**Comment by liihuu** [comment]
v8.6.0 已修复
