### ISSUE TITLE
Bug: Y axis layout

### ISSUE THREAD

**Issue by YuchuanGu** [liihuu/KLineChart#255]
添加主附图指标后，附图指标在面板外面了

this.kLineChart = init('motion-system-k-line')
this.kLineChart.createTechnicalIndicator('MA', false, { id: 'candle_pane' })
this.paneId = this.kLineChart.createTechnicalIndicator('MACD', false)

**Comment by liihuu** [comment]
暂时将图表容器样式避开 flex: 1，后续会修复这个问题

**Comment by YuchuanGu** [comment]
KLineChartSample/vuesample里面的container 样式本来就没有 flex:1 的

**Comment by YuchuanGu** [comment]
换个次序，排序就没有问题
this.kLineChart = init('motion-system-k-line')
this.paneId = this.kLineChart.createTechnicalIndicator('MACD', false)
this.kLineChart.createTechnicalIndicator('MA', true, { id: 'candle_pane' })

**Comment by YuchuanGu** [comment]
以下用例必现，tests/technical-indicator.html在 chart 外面包一层，



<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="keywords" content="kline time-line candlestick stock chart canvas k线 行情 蜡烛图 分时图 技术指标 图表"/>
    <meta name="description" content="shape test"/>
    <script type="text/javascript" src="../dist/klinecharts.min.js"></script>
    <script type="text/javascript" src="./js/dataSource.js"></script>
    <link rel="stylesheet" type="text/css" href="./css/chart.css"/>
    <title>技术指标</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div class="k-line-chart-container">
      <div id="chart"></div>
    </div>
    <script>
      window.onload = function () {
        var chart = klinecharts.init('chart')
        // 创建一个主图指标
        chart.createTechnicalIndicator('MA', false, { id: 'candle_pane' })
        // 创建一个主图指标叠加
        chart.createTechnicalIndicator('BOLL', true, { id: 'candle_pane' })
        // 创建一个副图指标
        chart.createTechnicalIndicator({ name: 'VOL', calcParams: [10], styles: { margin: { top: 0.2, bottom: 2 } } })
        // 创建一个副图指标
        chart.createTechnicalIndicator('MACD')
        chart.applyNewData(generated())
      }
    </script>
  </body>
</html>


以下是 css

.k-line-chart-container {
  float: left;
  display: flex;
  flex-direction: column;
  margin: 15px;
  border-radius: 2px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, .3);
  background-color: #FFFFFF;
  width: 620px;
  height: 600px;
  padding: 6px 8px 6px 8px;
}

**Comment by YuchuanGu** [comment]
以下用例必现，tests/technical-indicator.html在 chart 外面包一层，
`


<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="keywords" content="kline time-line candlestick stock chart canvas k线 行情 蜡烛图 分时图 技术指标 图表"/>
    <meta name="description" content="shape test"/>
    <script type="text/javascript" src="../dist/klinecharts.min.js"></script>
    <script type="text/javascript" src="./js/dataSource.js"></script>
    <link rel="stylesheet" type="text/css" href="./css/chart.css"/>
    <title>技术指标</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div class="k-line-chart-container">
      <div id="chart"></div>
    </div>
    <script>
      window.onload = function () {
        var chart = klinecharts.init('chart')
        // 创建一个主图指标
        chart.createTechnicalIndicator('MA', false, { id: 'candle_pane' })
        // 创建一个主图指标叠加
        chart.createTechnicalIndicator('BOLL', true, { id: 'candle_pane' })
        // 创建一个副图指标
        chart.createTechnicalIndicator({ name: 'VOL', calcParams: [10], styles: { margin: { top: 0.2, bottom: 2 } } })
        // 创建一个副图指标
        chart.createTechnicalIndicator('MACD')
        chart.applyNewData(generated())
      }
    </script>
  </body>
</html>
`

以下是 css

.k-line-chart-container {
  float: left;
  display: flex;
  flex-direction: column;
  margin: 15px;
  border-radius: 2px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, .3);
  background-color: #FFFFFF;
  width: 620px;
  height: 600px;
  padding: 6px 8px 6px 8px;
}

**Comment by YuchuanGu** [comment]
以下用例必现，tests/technical-indicator.html在 chart 外面包一层，

    <div class="k-line-chart-container">
      <div id="chart"></div>
    </div>

以下是 css

.k-line-chart-container {
  float: left;
  display: flex;
  flex-direction: column;
  margin: 15px;
  border-radius: 2px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, .3);
  background-color: #FFFFFF;
  width: 620px;
  height: 600px;
  padding: 6px 8px 6px 8px;
}

**Comment by liihuu** [comment]
试试v9
