### ISSUE TITLE
[Feature] Provide timestamps for Shape points in the future (beyond the right-most candle)

### ISSUE THREAD

**Issue by aelr** [liihuu/KLineChart#260]
### Feature Description

I'm trying to draw trend lines that extend into the future, using the segment Shape. However, `point[1].timestamp` on the segment is `undefined`. I expect that it's possible to determine the timestamp, even though it extends beyond the chart. I'm looking for a way to do so.

By the way, this library is awesome. Thank you for all of the hard work!

### To Do

Provide a value for timestamps even when they are off of the chart area.

**Comment by olablt** [comment]
I think you can set the timestamp and index values manually. I needed the segment shape to begin before the first data timestamp point. I left the timestamp undefined and assigned the negative index value - it worked.

**Comment by aelr** [comment]
I needed the actual timestamp values for use externally. I was able to solve the problem by adding a bunch of dummy candles to the right of the chart.

**Comment by aelr** [comment]
Creating the line does work. But I'm trying to get the timestamp value for the drawn line for external processing.
________________________________
