### ISSUE TITLE
[Bug] Time axis grid/label is off depending on the zoom level

### ISSUE THREAD

**Issue by trading-peter** [liihuu/KLineChart#269]
### Version

8.6.0

### Steps to Reproduce

Open the official kline example chart: https://klinecharts.com/sample
select the 1H timeframe and zoom in/out step by step until you see the time axis grid shifted onto different candles

### Current Behavior

In some zoom levels the time axis grid get's shifted by quite a few candels.

![image](https://user-images.githubusercontent.com/11567985/177947682-cfb1581e-64aa-472d-964b-e324631068b9.png)
![image](https://user-images.githubusercontent.com/11567985/177947908-360da39c-1d30-4b17-9f0c-331110c06c1c.png)

### Expected Behavior

The grid should stay on the right candle

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by liihuu** [comment]
Auto calc.
