### ISSUE TITLE
[Bug] scrollToTimestamp设置固定时间戳，连续触发k线会连续向前挪动，没有跳到指定时间戳

### ISSUE THREAD

**Issue by lililemon** [liihuu/KLineChart#278]
### 版本

8.6.1

### 复现步骤

使用官方模版,
调用chart.scrollToTimestamp(1658419262000)，时间戳随意，

### 当前效果

持续向前滚动

### 预期效果

跳转到指定的时间戳

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
v8.6.2 fixed it
