### ISSUE TITLE
[Feature] return Tag & Annotation after created

### ISSUE THREAD

**Issue by voladelta** [liihuu/KLineChart#282]
### Feature Description

Currently, there is no way to update Tag or Annotation after they are created. 

Because createAnnotation and createTag don't return their instance. 

And chart instance doesn't offer away to update them.

My use case is when user drag a price line, we will update a tag/annotation like SL, TP, or Alert for them. 

### To Do

Either return Tag & Annotation after created, or add setTagOptions and setAnnotationOptions like setShapeOptions.

Thank you for your hardwork on KLineChart, liihuu. 🤗

**Comment by liihuu** [comment]
Try v9.
