### ISSUE TITLE
[Feature] 如何将 annotationDrawExtend 画到 k 线的相对位置？

### ISSUE THREAD

**Issue by AGDholo** [liihuu/KLineChart#289]
### 需求描述

我参考了该例子的代码：https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/CustomCandleMarkKLineChart.jsx

发现只能将标记画到绝对位置，是否有 api 提供 k 线的位置？

想实现的标记效果类似于：https://klinecharts.com/zh-CN/sample

感谢。

### 具体实现

#

**Comment by liihuu** [comment]
样式设置`position: 'point'`.
