### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by edward677** [liihuu/KLineChart#292]
### Feature Description

vite创建的vue3.0项目无法使用klinecharts，没有报错

### To Do

希望解决

**Comment by liihuu** [comment]
如果报错，请贴出报错信息，如果没有，请检查一下元素，看是否真的有初始化成功。klinecharts零依赖，和框架没有太大关系

**Comment by edward677** [comment]
初始化成功
[image: 截屏2022-08-10 14.17.27.png]
检查过了
有klinecharts对象

lihu ***@***.***> 于2022年8月10日周三 14:50写道：

**Comment by edward677** [comment]
[image: 截屏2022-08-10 17.53.17.png]

时间轴已经绘画出来了，
没有任何报错
是用https://github.com/liihuu/KLineChartSample/tree/master/vue-sample 的模拟数据

lin edward ***@***.***> 于2022年8月10日周三 17:24写道：

**Comment by liihuu** [comment]
https://klinecharts.com/zh-CN/guide/faq#%E5%88%9D%E5%A7%8B%E5%8C%96%E5%9B%BE%E8%A1%A8%E5%90%8E%E5%8F%AA%E8%83%BD%E7%9C%8B%E5%88%B0%E4%B8%80%E6%9D%A1%E7%BA%BF%E6%98%AF%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B
