### ISSUE TITLE
[Feature] 可否将annotation进行分组管理

### ISSUE THREAD

**Issue by sharpAll** [liihuu/KLineChart#293]
### Feature Description

我这边创建了两种类型的注解，现在我希望将他们进行分组操作（隐藏、显示或者修改之类的）。
目前removeAnnotation方法只提供paneId和points维度上的操作，我这些注解都在candle_pane上而且不同类型的注解的timestamp可能是相同的。所以这个方法没法用。
![企业微信截图_16602008328590](https://user-images.githubusercontent.com/21251354/184079352-c956326e-06c2-4493-ab48-7ef1b9d6e55b.png)

### To Do

在createAnnotation和removeAnnotation时能否添加一个groupName的参数

**Comment by liihuu** [comment]
v9 alpha 已经发布，新增了 groupId，可以尝试一下。

**Comment by sharpAll** [comment]
非常感谢
