### ISSUE TITLE
[Feature] 能否新增一个K线的点击事件

### ISSUE THREAD

**Issue by sharpAll** [liihuu/KLineChart#297]
### 需求描述

我想双击某一个日K线时弹出当日的交易明细，文档里好像并没有这个api。

### 具体实现

新增一个点击K线的事件，返回的参数为所点击K线的时间戳。

**Comment by obxyann** [comment]
Yes, I am also looking how to hook a click on chart just like I can hook click on a shape (overlay)

**Comment by openroc** [comment]
+1

**Comment by lucasllin** [comment]
+1

**Comment by kesyn** [comment]
+1

**Comment by LiuCaptain** [comment]
+1

**Comment by AversonCoder** [comment]
+1

**Comment by liihuu** [comment]
v9.1.0  supported it.

**Comment by openroc** [comment]
> v9.1.0 supported it.

👍
