### ISSUE TITLE
setPrecision(pricePrecision, volumePrecision) not working on Y-Axis labels

### ISSUE THREAD

**Issue by th-pias** [liihuu/KLineChart#30]
I have set setPrecision(6, 2) and the precisions working on low, high, last price, and also on the crosshair price or volume count. But not working on Y-axis labels.
![Screenshot_from_2020_05_28_14_02_04](https://user-images.githubusercontent.com/10570398/83115710-9d4cbf00-a0ec-11ea-8673-390c9bd56a7b.png)

How to apply precision on Y-Axis labels (red marked on image)?

**Comment by liihuu** [comment]
The current y-axis accuracy will not be affected by the settings. The problem in the screenshot should be the reason for the consistent data. You can try to upgrade to v5.3.0. hope this helps.

**Comment by th-pias** [comment]
"The current y-axis accuracy will not be affected by the settings." - but I think there should be a function that provides us the facility to round y-axis labels.
I think setPrecision should affect the y-axis labels too.


BTW thanks for this great lib :)

**Comment by liihuu** [comment]
Version 5.5.0 has been released and this feature is already supported.
