### ISSUE TITLE
[Feature] 主图的tooltip里能不能新增一个涨跌幅

### ISSUE THREAD

**Issue by sharpAll** [liihuu/KLineChart#301]
### Feature Description

主图配置中candle的tooltip应该是不能自定义配置的吧，一般的K线图都会有一个百分比的涨跌幅，看上去比较直观。
涨跌的颜色如果能根据candle样式显示就更好了。
![企业微信截图_16612455427234](https://user-images.githubusercontent.com/21251354/186120111-a4688f43-cf7e-4730-84af-483296e402a2.png)

### To Do

tooltip中新增一个涨跌幅字段或者设为可自定义配置。
ps: 感谢大佬的无私奉献。

**Comment by liihuu** [comment]
样式配置里面labels结合values使用
示例：
https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/TooltipKLineChart.jsx

**Comment by sharpAll** [comment]
好的，非常感谢。

**Comment by yetrun** [comment]
> 样式配置里面labels结合values使用 示例： https://github.com/liihuu/KLineChartSample/blob/master/react-sample/src/chart/TooltipKLineChart.jsx

计算涨跌需要知道前一日的收盘价啊

**Comment by yetrun** [comment]
我提了一个新的 Issue，#384.
