### ISSUE TITLE
[Bug]  No type definitions for 'klinecharts/lib/mark/shapeHelper'

### ISSUE THREAD

**Issue by jinusean** [liihuu/KLineChart#303]
### Version

8.6.1

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/6874981/187024322-e4429843-a0b2-4377-a507-09f361447330.png)

### Current Behavior

Cannot import without `// @ts-ignore`

### Expected Behavior

Type definitions to allow imports.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

[Docs](https://klinecharts.com/api/shape) specify using `import { ... } from 'klinecharts/lib/mark/shapeHelper'`, but the correct path is `klinecharts/lib/shape/shapeHelper`, which also does not have typescript support

**Comment by liihuu** [comment]
Documentation has some errors.

**Comment by jinusean** [comment]
Not just the documentation but the typescript support as well.

**Comment by liihuu** [comment]
I will write the declaration file.

**Comment by liihuu** [comment]
V9 has been reconstructed with typescript, so don't worry about such problems.
