### ISSUE TITLE
[Bug] updateData() 添加新資料時 subscribeAction('crosshair') 收到的資料中, 指標內容是 undefined

### ISSUE THREAD

**Issue by chaosrx** [liihuu/KLineChart#306]
### 版本

8.6.1

### 复现步骤

var klineChart = klinecharts.init('chart-dk');
let VOL = klineChart.createTechnicalIndicator('VOL', false, { id: 'VOL'});
klineChart.subscribeAction('crosshair', onChartEvent_crosshair);

klineChart.updateData({...});

onChartEvent_crosshair(data) {
      // data.technicalIndicatorData.VOL.VOL is undefined
}

### 当前效果

N/A

### 预期效果

N/A

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
console一下看下格式。
