### ISSUE TITLE
初始化时，如果数据量过少，无法占满整个视图

### ISSUE THREAD

**Issue by newWebTimes** [liihuu/KLineChart#314]
### 需求描述

初始化时，如果数据量过少，无法占满整个视图
![image](https://user-images.githubusercontent.com/19962540/191487099-3e4d9eea-9171-4a5a-a400-2a976b8feb9f.png)

### 具体实现

resize无效

**Comment by lfcleo** [comment]
> ### 需求描述
> 初始化时，如果数据量过少，无法占满整个视图 ![image](https://user-images.githubusercontent.com/19962540/191487099-3e4d9eea-9171-4a5a-a400-2a976b8feb9f.png)
> 
> ### 具体实现
> resize无效

解决了吗？文档中没找到用哪个方法 @newWebTimes
