### ISSUE TITLE
[Feature] Draw Indicators/Shapes Behind Candles

### ISSUE THREAD

**Issue by jinusean** [liihuu/KLineChart#315]
### Feature Description

It is very difficult to see small candle prints when it overlaps with shapes/indicators.

Is there a way to draw the indicators _BEHIND_ the candles?

![image](https://user-images.githubusercontent.com/6874981/191555221-3d03508b-2e6e-4c15-8ec8-235128ce6ed5.png)

Small dojis behind the indicator lines makes it difficult to see its shape. 

### To Do

1. Option to draw indicator behind / in-front of candles.

**Comment by liihuu** [comment]
`ctx.globalCompositeOperation = 'destination-over'`
