### ISSUE TITLE
在可视区范围内，请问如何获取到最高值和最低值的信息

### ISSUE THREAD

**Issue by newWebTimes** [liihuu/KLineChart#316]
### 需求描述

![image](https://user-images.githubusercontent.com/19962540/191677345-a8fb06b8-61ee-4fad-8b40-77a0e052da92.png)

### 具体实现

如上

**Comment by liihuu** [comment]
暂不支持获取

**Comment by newWebTimes** [comment]
请问后续会支持吗，有些操作场景需要涉及到最大值和最小值，包括位置信息

**Comment by newWebTimes** [comment]
请问x轴的可视区内的两个点的时间戳可以获取到吗，文档内似乎没有提供这样的方法，如果能够获取可视区x轴两点的时间戳信息，应该也可以做一次过滤

**Comment by liihuu** [comment]
#299

**Comment by liihuu** [comment]
V9已支持
