### ISSUE TITLE
[Feature] Plot precalculated Technical Indicator Values

### ISSUE THREAD

**Issue by arul67800** [liihuu/KLineChart#320]
### Feature Description

Hi sir, i have a python program which already calculates technical Indicator, i want to display that to chart which was calculated in backend through websockets or api...please guide.....and Thank you for this piece of Art

**Comment by liihuu** [comment]
Supporting remote computing requires returning a promise.

**Comment by arul67800** [comment]
Sir.. I would be grateful if u give me a example

**Comment by QGB** [comment]
@arul67800 any code example？
