### ISSUE TITLE
[Feature] How to use renko candle style?

### ISSUE THREAD

**Issue by ahbapAldirmaz** [liihuu/KLineChart#321]
### Feature Description

I don't know if there is a Renko candle feature. 
But if so, how do we do it? 
Can you give a live example? 
Or are you considering adding this feature?

Here is the ready calculation function of Renko.
[https://github.com/anandanand84/technicalindicators/blob/master/lib/chart_types/Renko.js](https://github.com/anandanand84/technicalindicators/blob/master/lib/chart_types/Renko.js)
But the data structure it generates is a little different.

### To Do

Renko Candle Style.

**Comment by guelweles** [comment]
I also would love to have renko in this amazing library, the more features the better, not only renko but Heiken Ashi as well.

**Comment by guelweles** [comment]
I did manage to create my own custom renko function, here's the outcome.

![image](https://user-images.githubusercontent.com/71226782/202236172-fa3475aa-90b7-4e6d-9959-86ef825a9572.png)

The only issue is that the function updateData() relies on timestamp, if it's the same timestamp it overrides the current candle, if it's a new one, a new candle is added into the  data array.

I tried to modify the timestamp to see if the updatDate() would play nice, but it didn't work, I tried something like timestamp = timestamp + 10.

I managed to update the chart in a different way, by clearing the data and the applying it again.
```
const source = [....]
const containerId = 'chartContainer';
const chart = init(containerId);

// Draw chart
chart.applyNewData(source)

// For updates after the renko function returns new data
chart.clearData();
chart.applyNewData(newData);
````

It' be nice if the updateData() function, could take an argument so we could tell what field it should use (timestamp, close and so on) in order to update data,  renko chart does not rely on timestamp but price moves.

@liihuu 
Do you think this could be added into future releases?

I also managed to create a function to draw heikin ashi candles, I'm no expert to try to apply them into the library so that they could be native functions.

I can share all code if that helps

Here's the heikin ashi

![image](https://user-images.githubusercontent.com/71226782/202240128-4e22d384-d98a-475c-8743-b3a494bc4e87.png)

I'd appreciate having them into future releases, this library is by far the best I found on the internet, thanks for the good work.

**Comment by ahbapAldirmaz** [comment]
Of course it helps. Can you share Renko and Heiken Ashi codes.

**Comment by guelweles** [comment]
### Renko Code

````
function calcRenko(ohlc, brickSize, precision) {
    let renkoData = [];
    let previousClosePrice = ohlc[0].open;

    for (let i = 1; i < ohlc.length; i++) {
        const openTime = ohlc[i].timestamp;
        const closePrice = ohlc[i].close;
        const difference = Number((closePrice - previousClosePrice).toFixed(precision));

        if (difference > 0 && difference > brickSize) {
            for (let j = 0; j < Math.floor(difference / brickSize); j++) {
                const newClosePrice = Number((previousClosePrice + brickSize).toFixed(precision));
                const highAndLow = previousClosePrice < newClosePrice ? [newClosePrice, previousClosePrice] : [previousClosePrice, newClosePrice];

                const obj = {
                    open: previousClosePrice,
                    high: highAndLow[0],
                    low: highAndLow[1],
                    close: newClosePrice,
                    timestamp: openTime
                }

                if (renkoData.length === 0) {
                    renkoData.push(obj);
                } else {
                    if (newClosePrice !== renkoData.at(-1).open && newClosePrice !== renkoData.at(-1).close) {
                        renkoData.push(obj);
                    }
                }


                previousClosePrice = newClosePrice;
            }
        } else if (difference < 0 && Math.abs(difference) > brickSize) {
            for (let j = 0; j < Math.floor(Math.abs(difference) / brickSize); j++) {
                const newClosePrice = Number((previousClosePrice - brickSize).toFixed(precision));
                const highAndLow = previousClosePrice < newClosePrice ? [newClosePrice, previousClosePrice] : [previousClosePrice, newClosePrice];

                const obj = {
                    open: previousClosePrice,
                    high: highAndLow[0],
                    low: highAndLow[1],
                    close: newClosePrice,
                    timestamp: openTime
                };

                if (renkoData.length === 0) {
                    renkoData.push(obj);
                } else {
                    if (newClosePrice !== renkoData.at(-1).open && newClosePrice !== renkoData.at(-1).close) {
                        renkoData.push(obj);
                    }
                }

                previousClosePrice = newClosePrice;
            }
        }
    }

    return renkoData;
}

function updateRenko(currentCandle, renkoData, brickSize, precision) {
    let newRenkoData = [...renkoData];
    let previousClosePrice = newRenkoData.at(-1).close;

    const openTime = currentCandle.timestamp + 10;
    let closePrice = currentCandle.close;
    const difference = Number((closePrice - previousClosePrice).toFixed(precision));

    if (difference > 0 && difference > brickSize) {
        for (let j = 0; j < Math.floor(difference / brickSize); j++) {
            const newClosePrice = Number((previousClosePrice + brickSize).toFixed(precision));
            const highAndLow = previousClosePrice < newClosePrice ? [newClosePrice, previousClosePrice] : [previousClosePrice, newClosePrice];

            const obj = {
                open: previousClosePrice,
                high: highAndLow[0],
                low: highAndLow[1],
                close: newClosePrice,
                timestamp: openTime
            }

            if (newRenkoData.length === 0) {
                newRenkoData.push(obj);
            } else {
                if (newClosePrice !== newRenkoData.at(-1).open && newClosePrice !== newRenkoData.at(-1).close) {
                    newRenkoData.push(obj);
                }
            }

            previousClosePrice = newClosePrice;
        }
    } else if (difference < 0 && Math.abs(difference) > brickSize) {
        for (let j = 0; j < Math.floor(Math.abs(difference) / brickSize); j++) {
            const newClosePrice = Number((previousClosePrice - brickSize).toFixed(precision));
            //const newClosePrice = globalFunctions.cutOffLength(previousClosePrice - brickSize, priceStep);

            const highAndLow = previousClosePrice < newClosePrice ? [newClosePrice, previousClosePrice] : [previousClosePrice, newClosePrice];

            const obj = {
                open: previousClosePrice,
                high: highAndLow[0],
                low: highAndLow[1],
                close: newClosePrice,
                timestamp: openTime
            };

            if (newRenkoData.length === 0) {
                newRenkoData.push(obj);
            } else {
                if (newClosePrice !== newRenkoData.at(-1).open && newClosePrice !== newRenkoData.at(-1).close) {
                    newRenkoData.push(obj);
                }
            }

            previousClosePrice = newClosePrice;
        }
    }

    return newRenkoData;
}
`````
Bellow is how I cal the renko function

````
const brickSize = 0.0095;
const initial = calcRenko(ohlc, brickSize, 4);
const update = updateRenko(ohlc.at(-1), initial, brickSize, 4)

console.log(initial.at(-1))
console.log(update.at(-1));
````

Both console logs should return the same values since I'm not changing any data, I was trying to add an option to have renko also based on OHLC and not only based on close prices, like tradingview does, but I'm still struggling with it.

Brick size is up to the user, it could also be based on ATR but I prefer fixed brick sizes, 

````
function calcATR(period, prices, precision) {
    technicalIndicators.setConfig('precision', precision);

    const data = { high: [], low: [], close: [] };

    prices.forEach(item => {
        data.high.push(item.high);
        data.low.push(item.low);
        data.close.push(item.close);
    })

    return new technicalIndicators.ATR({ "period": period, "high": data.high, "low": data.low, "close": data.close });
}

const calcBrickSize = Number((calcATR(14, ohlc, 4).getResult().at(-1)).toFixed(4));
````

**Comment by guelweles** [comment]
### Heikin Ashi Code

````
function calcHeikinAshi(ohlc, precision) {
    let HA = [];

    for (let i = 0; i < ohlc.length; i++) {
        const { open, high, low, close, volume, timestamp } = ohlc[i];
        if (i === 0) {
            HA.push({
                "open": Number(((open + close) / 2).toFixed(precision)),
                "high": Number(high.toFixed(precision)),
                "low": Number(low.toFixed(precision)),
                "close": Number(((open + high + low + close) / 4).toFixed(precision)),
                "volume": volume,
                "timestamp": timestamp,
            })
        } else {
            HA.push({
                "open": Number(((HA.at(-1).open + HA.at(-1).close) / 2).toFixed(precision)),
                "high": Number(Math.max(high, HA.at(-1).open, HA.at(-1).close).toFixed(precision)),
                "low": Number(Math.min(low, HA.at(-1).open, HA.at(-1).close).toFixed(precision)),
                "close": Number(((open + high + low + close) / 4).toFixed(precision)),
                "volume": volume,
                "timestamp": timestamp,
            })
        }
    }

    return HA;
}

function updateHeikinAshi(currentOHLC, HA, precision) {
    const { open, high, low, close, volume, timestamp } = currentOHLC;

    const obj = {
        "open": Number(((HA.at(-2).open + HA.at(-2).close) / 2).toFixed(precision)),
        "high": Number(Math.max(high, HA.at(-2).open, HA.at(-2).close).toFixed(precision)),
        "low": Number(Math.min(low, HA.at(-2).open, HA.at(-2).close).toFixed(precision)),
        "close": Number(((open + high + low + close) / 4).toFixed(precision)),
        "volume": volume,
        "timestamp": timestamp,
    }

    timestamp === HA.at(-1).timestamp ? HA[HA.length - 1] = obj : HA.push(obj);

    return HA
}
````

Calling the functions

````
const initial = calcHeikinAshi(ohlc, 4);
const update = updateHeikinAshi(ohlc.at(-1), initial, 4);

console.log(initial.at(-1));
console.log(update.at(-1));
````

ohlc is an array of objects

````
const ohlc = [
    {
        "timestamp": 1668564720000,
        "open": 2.0266,
        "high": 2.0268,
        "low": 2.025,
        "close": 2.0264,
        "volume": 692
    },
    {
        "timestamp": 1668564780000,
        "open": 2.0251,
        "high": 2.0273,
        "low": 2.0251,
        "close": 2.0253,
        "volume": 2652
    }
    ....
]
````

**Comment by zetzetto** [comment]
> ### Heikin Ashi Code
> 
> ```
> function calcHeikinAshi(ohlc, precision) {
>     let HA = [];
> 
>     for (let i = 0; i < ohlc.length; i++) {
>         const { open, high, low, close, volume, timestamp } = ohlc[i];
>         if (i === 0) {
>             HA.push({
>                 "open": Number(((open + close) / 2).toFixed(precision)),
>                 "high": Number(high.toFixed(precision)),
>                 "low": Number(low.toFixed(precision)),
>                 "close": Number(((open + high + low + close) / 4).toFixed(precision)),
>                 "volume": volume,
>                 "timestamp": timestamp,
>             })
>         } else {
>             HA.push({
>                 "open": Number(((HA.at(-1).open + HA.at(-1).close) / 2).toFixed(precision)),
>                 "high": Number(Math.max(high, HA.at(-1).open, HA.at(-1).close).toFixed(precision)),
>                 "low": Number(Math.min(low, HA.at(-1).open, HA.at(-1).close).toFixed(precision)),
>                 "close": Number(((open + high + low + close) / 4).toFixed(precision)),
>                 "volume": volume,
>                 "timestamp": timestamp,
>             })
>         }
>     }
> 
>     return HA;
> }
> 
> function updateHeikinAshi(currentOHLC, HA, precision) {
>     const { open, high, low, close, volume, timestamp } = currentOHLC;
> 
>     const obj = {
>         "open": Number(((HA.at(-2).open + HA.at(-2).close) / 2).toFixed(precision)),
>         "high": Number(Math.max(high, HA.at(-2).open, HA.at(-2).close).toFixed(precision)),
>         "low": Number(Math.min(low, HA.at(-2).open, HA.at(-2).close).toFixed(precision)),
>         "close": Number(((open + high + low + close) / 4).toFixed(precision)),
>         "volume": volume,
>         "timestamp": timestamp,
>     }
> 
>     timestamp === HA.at(-1).timestamp ? HA[HA.length - 1] = obj : HA.push(obj);
> 
>     return HA
> }
> ```
> 
> Calling the functions
> 
> ```
> const initial = calcHeikinAshi(ohlc, 4);
> const update = updateHeikinAshi(ohlc.at(-1), initial, 4);
> 
> console.log(initial.at(-1));
> console.log(update.at(-1));
> ```
> 
> ohlc is an array of objects
> 
> ```
> const ohlc = [
>     {
>         "timestamp": 1668564720000,
>         "open": 2.0266,
>         "high": 2.0268,
>         "low": 2.025,
>         "close": 2.0264,
>         "volume": 692
>     },
>     {
>         "timestamp": 1668564780000,
>         "open": 2.0251,
>         "high": 2.0273,
>         "low": 2.0251,
>         "close": 2.0253,
>         "volume": 2652
>     }
>     ....
> ]
> ```

Thank you.

**Comment by benoist** [comment]
Did this ever get added? I don't see it :)
