### ISSUE TITLE
[Bug] Candles Get Squished

### ISSUE THREAD

**Issue by jinusean** [liihuu/KLineChart#324]
### Version

8.6.1

### Steps to Reproduce

https://user-images.githubusercontent.com/6874981/194611495-25e00708-f274-4f21-9856-a5866087ccc0.mov

1. Scroll chart 
2. Candles get squished at certain ranges.

### Current Behavior

Candles are getting squished.

### Expected Behavior

Candles should maintain range height

### Environment

```markdown
- OS: Mac Montery
- Browser: 
- Framework:
```

**Comment by jinusean** [comment]
[candles.txt](https://github.com/liihuu/KLineChart/files/9736113/candles.txt)
Candles data that triggers this error.

**Comment by jinusean** [comment]
This seems to happen only when yaxis is set to 'log'

**Comment by jinusean** [comment]
Unfortunately that didn't do the trick.
Some assets get squished in 'log' mode, while others do not, and the opposite happens when yAxis is set to 'normal'.
Would really appreciate your feedback @liihuu

**Comment by pengshuai628** [comment]
@jinusean 请问有解决该问题吗

**Comment by liihuu** [comment]
V9 supported vertical scaling.
