### ISSUE TITLE
[Bug] 技术指标line特定情况下无法显示

### ISSUE THREAD

**Issue by peterzhou84** [liihuu/KLineChart#326]
### 版本

8.6.0

### 复现步骤

// [KLineChart](https://github.com/liihuu/KLineChart)/[src](https://github.com/liihuu/KLineChart/tree/main/src)/[view](https://github.com/liihuu/KLineChart/tree/main/src/view)/TechnicalIndicatorView.js

// Latest commit [cb5d782](https://github.com/liihuu/KLineChart/commit/cb5d78229545da96da322471655a8fc66eed51ed) on 26 Jun

// line 201
```
if (isValid(value)) {
...
    if (i === to - 1) {
                      lines.push({
                        color: _plotStyle2.color,
                        isDashed: _plotStyle2.isDashed,
                        coordinates: lineCoordinates[lineCount]
                      });
    }
}
```
上面的代码当line的最后一个value无效时，lines没有被push进数据，导致line无法显示出来。

### 当前效果

当技术指标最后一个值invalid时技术指标无法显示

### 预期效果

当技术指标最后一个值invalid时技术指标正常显示

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
使用自定义绘制
