### ISSUE TITLE
datasource中有个远大于当前数据段平均值时，也就是k线被插针的情况下，会出现k线幅度异常。

### ISSUE THREAD

**Issue by ShowPenZ** [liihuu/KLineChart#33]
datasource中有个远大于当前数据段平均值时，也就是k线被插针的情况下，若预加载的数组内含有这样的数据时，即使没在屏幕中显示也会导致k线幅度异常![image.png](https://i.loli.net/2020/06/02/5YMKqBvortVXGRN.png) ![image.png](https://i.loli.net/2020/06/02/NU5vewsofLkE2PS.png)

**Comment by liihuu** [comment]
插针即使不显示也会影响到均线的值，y轴最大最小会取当前所有显示数据的最大最小值。

**Comment by ShowPenZ** [comment]
假设取400条数据，插针在第200条位置左右会导致前面的k线幅度太小，观测的话就不太友好

**Comment by liihuu** [comment]
可以不设置均线

**Comment by ShowPenZ** [comment]
请问下如何不设置均线，是哪个api文档中没看到
