### ISSUE TITLE
[Feature] 当在小屏幕时，副图指标过多，主图蜡烛图提示方框被截断

### ISSUE THREAD

**Issue by AversonCoder** [liihuu/KLineChart#337]
### Feature Description

![image](https://user-images.githubusercontent.com/13031684/204952774-550719a9-34c3-4d17-a2e6-9e67382dcf59.png)

如图所示，高开低收显示不全。

源码目前貌似直接附着在主图。是否有方式设置成如下图红框内的展示。

![image](https://user-images.githubusercontent.com/13031684/204953216-951fcf64-e777-4cbd-9650-e7d6d014d020.png)

### To Do

TODO

**Comment by AversonCoder** [comment]
感谢作者百忙中抽空回复，目前的打算的处理方案是：

- 当附图指标达到一定数量后，主图定高以便于能完全展示数据提示框。
- 当附图指标达到一定数量后，缩放数据提示框文字大小等。

不起另外一个议题，请问作者当点击范围超出图后，十字线能否定位在最后一条，而不是在数据外。看过源码的 Overlay 似乎不太好改没什么思路。非常感谢。

#152 与该 issue 一致。

**Comment by liihuu** [comment]
> 感谢作者百忙中抽空回复，目前的打算的处理方案是：
> 
> * 当附图指标达到一定数量后，主图定高以便于能完全展示数据提示框。
> * 当附图指标达到一定数量后，缩放数据提示框文字大小等。
> 
> 不起另外一个议题，请问作者当点击范围超出图后，十字线能否定位在最后一条，而不是在数据外。看过源码的 Overlay 似乎不太好改没什么思路。非常感谢。
> 
> #152 与该 issue 一致。

暂不支持

**Comment by AversonCoder** [comment]
好的，感谢您。
