### ISSUE TITLE
[Feature] 求支持“神奇九转”指标（Magic NINE）

### ISSUE THREAD

**Issue by zfhstudy** [liihuu/KLineChart#344]
### 需求描述

看了kline chart确实不错，也支持不少指标扩展，能否支持一下国内股民比较熟悉的“神奇九转”指标（Magic NINE）

### 具体实现

同花顺、富途牛牛App是有支持“神奇九转”指标（Magic NINE），虽然效果简单但用户很喜欢

**Comment by liihuu** [comment]
自定义指标可以实现。
