### ISSUE TITLE
[Feature] createHtml(html, paneId) 的 position 不支持 xAxis 位置

### ISSUE THREAD

**Issue by LiuCaptain** [liihuu/KLineChart#345]
### 需求描述

我要在kline图上 xAxis 组件上自定义一些html,但目前该API不能支持

### 具体实现

我要在kline图上 xAxis 组件上自定义一些html,但目前该API不能支持，我觉得可以能满足像 position,在content和yAxis 的功能就够

**Comment by liihuu** [comment]
V9通过`getDom`获取到指定的元素，然后进行操作即可。
