### ISSUE TITLE
[Feature] 当我们使用createAnnotation创建多个Annotation，创建的Annotation显示先后顺序没法控制

### ISSUE THREAD

**Issue by LiuCaptain** [liihuu/KLineChart#346]
### 需求描述

当我们使用createAnnotation创建多个Annotation，创建的Annotation显示先后顺序没法控制

希望可以实现创建的Annotation，当存在多个Annotation在重叠时，可以控制Annotation的显示先后

### 具体实现

- 动态控制绘制Annotation先后

**Comment by yizhipiju** [comment]
我通过createAnnotation  自定义创建图标之后，移动图表chart，会自动重复绘制图标，导致一排全是图标，有大佬知道怎么解决吗

**Comment by liihuu** [comment]
v9.4.0支持用zLevel控制层级
