### ISSUE TITLE
[Bug] Chart freezes during times of high volatility

### ISSUE THREAD

**Issue by jinusean** [liihuu/KLineChart#347]
### Version

8.6.3

### Steps to Reproduce

During times when the market experiences a lot of volatility (a lot of [new] candle updates).

### Current Behavior

The chart becomes very slow and does not respond to user input.

### Expected Behavior

Ideally there should be no lag.
I currently use a throttler for `updateData` but I have to call the function immediately whenever a new candle is formed since the `updateData` function only accepts one candle at a time (I am using tick charts).

Is there a way for `updateData` to accept more than one candle a time so I can throttle multiple new candles at once?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by liihuu** [comment]
Best practice: Merge multiple pieces of data before adding to the chart to reduce the frequency of updates.

**Comment by jinusean** [comment]
Yea I normally do that if the new candles has the same timestamp, but tick/volume charts requires each candle to have a specific number of transactions/volume.

Is there a way to `updateData` with more than one candle?
