### ISSUE TITLE
手机QQ浏览器不兼容

### ISSUE THREAD

**Issue by H-Sven** [liihuu/KLineChart#35]
this.chart = init(document.querySelector('#container_id'))

初始化的时候出错，其他浏览器没有这个问题，只有手机QQ浏览器

![VBQJU$0%I`P}9{RO 4OPSLW](https://user-images.githubusercontent.com/26042365/83865737-35841d00-a759-11ea-811b-85d8efc38bc4.png)

![Snipaste_2020-06-05_18-19-52](https://user-images.githubusercontent.com/26042365/83865712-2c934b80-a759-11ea-9375-68b05872ca28.png)

**Comment by scriptpower** [comment]
`this.chart = init('container_id')`

**Comment by H-Sven** [comment]
> `this.chart = init('container_id')`

一样的

**Comment by liihuu** [comment]
文档里面有兼容方案，尝试引入Intl.js
