### ISSUE TITLE
[Feature] Draggable tags

### ISSUE THREAD

**Issue by ntftrader** [liihuu/KLineChart#352]
### Feature Description

Feature request (or implementation advice). See also #282 and #251

The screenshot shows an example programmatically using `Tag` for chart trading (bracket trading). However `Tag` do not have any drag/drop or other callbacks like `Shape` but has the essential layout both `mark`, price indicator and full length line.

![Screenshot_20230103_145643](https://user-images.githubusercontent.com/19326175/210403003-70dc2e70-e550-48eb-88f0-307bbe104370.png)

### To Do

1. Could `Tag` inherit from `Shape` instead?
2. Or should there be a custom inherited from `Shape` like `DraggableTag`?

**Comment by liihuu** [comment]
V9-alpha has been released. You can try to `createOverlay('simpleTag')` or customize overlay.
