### ISSUE TITLE
有没有小伙伴遇到在vue中setStyleOptions无法手动更新的问题

### ISSUE THREAD

**Issue by xintains** [liihuu/KLineChart#355]
### 版本

8.6.3

### 复现步骤

同样的样式配置，我在原生js中手动更新样式没什么问题，例如控制背景的网格是否显示。但是在vue中第一次手动更新没什么问题，但是后面就没有作用了，我查看了数据确实是在变化的。vue的虚拟dom等问题我也是考虑了的，例如更新放在nextTick中更新，或者实时生成一个样式配置，都没什么用。实在想不到该怎么解决了，有遇到的大佬求帮助，谢谢。

### 当前效果

见上

### 预期效果

见上

### 环境

```markdown
- 系统:window
- 浏览器:chorm
- 框架:vue3
```

**Comment by NameWjp** [comment]
描述看不出什么问题，如果有最小复现的demo就好排查了

**Comment by liihuu** [comment]
提供下核心代码。
