### ISSUE TITLE
[Bug] vue的vant组件库，如果吧K线放在tab标签页组件里，就无法显示，高度有，就是没数据

### ISSUE THREAD

**Issue by molaina-oiu** [liihuu/KLineChart#356]
### 版本

9

### 复现步骤

`<van-tabs v-model:active="active" shrink>
        <van-tab title="交易">

        </van-tab>
        <van-tab title="数据图">
          
          <div class="chart-index-kChart">
            <KChart></KChart>
          </div>
          
        </van-tab>
      </van-tabs>`

### 当前效果

只显示出了一个X轴的线，好像是数据没有渲染出来

### 预期效果

显示完全

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
tab切换建议重新初始化
