### ISSUE TITLE
[Bug] chrome英文版浏览器，klinecharts使用v9版本设置locale为中文简体无效，图表字眼还是英文

### ISSUE THREAD

**Issue by zfhstudy** [liihuu/KLineChart#358]
### 版本

9.0

### 复现步骤

![image](https://user-images.githubusercontent.com/8468665/213118949-7638158a-232b-4473-a821-7f7299e7bbce.png)
麻烦帮忙看看这个本地化的选项设置为啥没生效，在英文版Chrome浏览器

### 当前效果

麻烦帮忙看看这个本地化的选项设置为啥没生效，在英文版Chrome浏览器

### 预期效果

显示中文字眼

### 环境

```markdown
- 系统:MacOS
- 浏览器:Chrome 108版本
- 框架:
```

**Comment by liihuu** [comment]
zh-CN

**Comment by zfhstudy** [comment]
> 

一样的，没效果
![image](https://user-images.githubusercontent.com/8468665/213119888-4765f4ff-fcf8-4d46-b249-35d048ca7e54.png)

**Comment by liihuu** [comment]
```init(`${domId}`, {  locale: 'zh-CN', styles:  { ... } })```

**Comment by zfhstudy** [comment]
> `` init(`${domId}`, { locale: 'zh-CN', styles: { ... } }) ``

多谢，搞定！
