### ISSUE TITLE
[Bug] 通过程序从dark切换成light网格线却没变回白色样式，还是黑色线

### ISSUE THREAD

**Issue by zfhstudy** [liihuu/KLineChart#360]
### 版本

9.0

### 复现步骤

通过程序从dark切换成light网格线却没变回白色样式，还是黑色线
![image](https://user-images.githubusercontent.com/8468665/213173449-9f6ab76c-0541-4aef-8271-5fe5c889f064.png)

### 当前效果

通过程序从dark切换成light网格线却没变回白色样式，还是黑色线

### 预期效果

正常light样色的网格线是这样的
![image](https://user-images.githubusercontent.com/8468665/213173486-386e14c1-aec2-4765-a8ac-b85bc6ae9d3b.png)

### 环境

```markdown
- 系统:MacOS
- 浏览器:Chrome v108
- 框架:
```

**Comment by liihuu** [comment]
v9.0.0-alpha6 已修复该问题。
