### ISSUE TITLE
[Bug] registerFigure typo error.

### ISSUE THREAD

**Issue by zetzetto** [liihuu/KLineChart#361]
### Version

9.0.0-alpha5

### Steps to Reproduce

There is a Typo error in function name: instead of registerFigure the function name is reisterFigure . Notice letter g is missing.

### Current Behavior

I can't run the code using registerFigure as it states in the documentation.

### Expected Behavior

The function name should be registerFigure

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by liihuu** [comment]
v9.0.0-alpha6 fixed it.
