### ISSUE TITLE
[Bug] 同样的是传入时间戳作为横坐标，极个别手机呈现的时间有问题

### ISSUE THREAD

**Issue by LiuCaptain** [liihuu/KLineChart#368]
### 版本

8.6.3

### 复现步骤

极个别手机横坐标出现“（China”，但大多数手机呈现正常

背景：我们做的国际化项目，是不是与时区有关

### 当前效果

![image](https://user-images.githubusercontent.com/43247357/215279410-205b571d-15b5-4610-82bf-a86d2567701e.png)

### 预期效果

正产呈现时间

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
https://klinecharts.com/zh-CN/guide/environment#intljs  先看下这个
