### ISSUE TITLE
[Bug] 文档Bug,部分API在【https://klinecharts.com/api/instance】文档中查找不到

### ISSUE THREAD

**Issue by LiuCaptain** [liihuu/KLineChart#371]
### 版本

https://klinecharts.com/api/instance

### 复现步骤

官方文档 【https://klinecharts.com/api/instance】 中，有部分API找不到，比如 **createAnnotation** 这个**API**，如下：

![image](https://user-images.githubusercontent.com/43247357/215689914-5d38603a-6dd8-4887-bdea-ca1af783bee6.png)

但是，在输入框中搜索是可以搜索到的

![image](https://user-images.githubusercontent.com/43247357/215690132-849af549-a30c-4774-8128-cd8582c20b63.png)

### 当前效果

Instance API不够完整，部分API在这个文档中找不到

### 预期效果

展现所有实例API

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
v8看对应的v8的文档
