### ISSUE TITLE
[Feature] 创建的 Annotation 在显示和隐藏时没法添加动画效果

### ISSUE THREAD

**Issue by LiuCaptain** [liihuu/KLineChart#372]
### 需求描述

当K线数据回来很快，画布不断的重新绘制，我们使用createAnnotation方法中的

drawExtend: function ({
    **ctx**,
    point,
    coordinate,
    viewport,
    isActive,
    styles,
  }) {
    console.log(point, coordinate, viewport, isActive, styles);
  }

在返回的 **ctx** 中绘制额外的画布内容，绘制的额外画布内容没法添加动画效果

### 具体实现

目前插件每次updateData数据时，画布是重新绘制，导致我们拿到ctx中添加的额外画布内容目前没法添加动画效果，期待实现

**Comment by liihuu** [comment]
#369
