### ISSUE TITLE
[Bug] 蜡烛图的某个柱子上创建多个注解时所存在的问题

### ISSUE THREAD

**Issue by LiuCaptain** [liihuu/KLineChart#373]
### 版本

8.6.3

### 复现步骤

当在蜡烛图的某根蜡烛上创建多个注解时，比如5分钟一根蜡烛，用户在这根蜡烛中买了5单，我们创建了5个注解进行标记，但是当清除其中一个注解，剩下4个注解都会被清除

原因：当 removeAnnotation 时，传入的是横坐标，也就是时间戳，导致该时间戳上的所有注解都会被清除

### 当前效果

removeAnnotation 会清除该 时间戳 上的所有注解

### 预期效果

期待能给 removeAnnotation 传入相关标注性参数，即使在同一横坐标，也不会清除该横坐标上的其他注解

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
v9可以完成需求
