### ISSUE TITLE
[Feature] 给一个点添加多个注解如何控制注解的offset或者位置？

### ISSUE THREAD

**Issue by FairyWorld** [liihuu/KLineChart#379]
### Feature Description

给一个点添加多个注解如何控制注解的offset或者位置？
现在一点点多个注解时，注解的位置一样会互相覆盖

### To Do

给一个点添加多个注解如何控制注解的offset或者位置？
现在一点点多个注解时，注解的位置一样会互相覆盖

**Comment by liihuu** [comment]
v9通过自定义覆盖物，自定义样式可以实现
