### ISSUE TITLE
十字准心移到某个K柱上后再移开图表区域,顶部的开高低收等数据还停留在了之前的那根K线上，没有回到最新的K线

### ISSUE THREAD

**Issue by H-Sven** [liihuu/KLineChart#38]
十字准心移到某个K柱上后再移开图表区域,顶部的开高低收等数据还停留在了之前的那根K线上，没有回到最新的K线

tradingView没有这个问题，火币基础版的K线图也没有这个问题

**Comment by liihuu** [comment]
5.5.0版本已支持。
