### ISSUE TITLE
[Bug] Typescript errors in options object

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#382]
### Version

9.0.0-alpha7

### Steps to Reproduce

```js
const options: Options = {
  locale: '',
  timezone: '',
  styles: {
    grid: {
      show: true,
      horizontal: {
        show: true,
        size: 1,
        color: '#EDEDED',
        style: "dashed",
        dashedValue: [2, 2]
      },
    ...
```

On horizontal.style for example:

> Type '"dashed"' is not assignable to type 'DeepPartial<LineType> | undefined'.ts(2322)

I can't use a string directly, and I can't import `LineType` because it is a [const enum](https://ncjamieson.com/dont-export-const-enums/).

### Current Behavior

Typescript errors for all options fields that reference a const enum. 

### Expected Behavior

No typescript errors. :)

**Comment by liihuu** [comment]
Fixed it.
