### ISSUE TITLE
[Bug] Crosshair vertical is using horizontal styles

### ISSUE THREAD

**Issue by DeeeeLAN** [liihuu/KLineChart#383]
### Version

9.0.0-alpha7

### Steps to Reproduce

See here: https://github.com/liihuu/KLineChart/blob/0ffb9a8e4d4535d93dbcb9a27c272207d8b7c8a1/src/view/CrosshairLineView.ts#L30-L48

### Current Behavior

Trying to style the vertical cursor is not possible at the moment since it copies the horizontal cursor configuration.

### Expected Behavior

Separate styling.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by liihuu** [comment]
Fixed it.
