### ISSUE TITLE
[BUG] Can't drag chart view on firefox.

### ISSUE THREAD

**Issue by itzTheMeow** [liihuu/KLineChart#386]
On [tradingview](https://www.tradingview.com/chart/) charts you can drag left to right to move the X axis. You can't do this on the [kline](https://klinecharts.com/sample) charts.
Is there a way to allow dragging the view on the x axis?

**Comment by itzTheMeow** [comment]
I see this is a bug related to firefox. I am able to drag the chart using chrome, but not firefox.

**Comment by zetzetto** [comment]
> I see this is a bug related to firefox. I am able to drag the chart using chrome, but not firefox.

This bug wasn't there before, it's probably something new emerged since the sample has been ported to version 9. But this problem doesn't exists in the library when you use it, because I use version 9 and I can drag it.

**Comment by guelweles** [comment]
I am facing the same issue, on Firefox I can't drag the chart on the X axis, on Chrome it does work but as soon as I drag either to left or right, the chart gets back to its initial position.

**Comment by guelweles** [comment]
> > I am facing the same issue, on Firefox I can't drag the chart on the X axis, on Chrome it does work but as soon as I drag either to left or right, the chart gets back to its initial position.
> 
> Have you actually used the klinechart in your own code or do you also mean the klinecharts sample ?
 
My own code, it's been a bit hard to upgrade from v8 to v9.

**Comment by zetzetto** [comment]
> > > I am facing the same issue, on Firefox I can't drag the chart on the X axis, on Chrome it does work but as soon as I drag either to left or right, the chart gets back to its initial position.
> > 
> > 
> > Have you actually used the klinechart in your own code or do you also mean the klinecharts sample ?
> 
> My own code, it's been a bit hard to upgrade from v8 to v9.

Must be something to do with the latest version. I use 9.0.0-alpha5 and with firefox I have no problem. Try one of previous relases.

**Comment by liihuu** [comment]
This is a very serious bug. I already know why. Fix it immediately.

**Comment by just-rich** [comment]
This is a huge issue, didn't notice until now as I use Chrome. Can someone please patch this ASAP?

**Comment by zetzetto** [comment]
> This is a huge issue, didn't notice until now as I use Chrome. Can someone please patch this ASAP?

It looks like fixed already.

**Comment by itzTheMeow** [comment]
It seems that drawing lines also does not function properly on firefox. (im testing this on the sample on the website)

I can click on a line but the chart freezes. If i scroll, the line moves to the position of my cursor but i can't move it otherwise and can't place it down.

**Comment by zetzetto** [comment]
> It seems that drawing lines also does not function properly on firefox. (im testing this on the sample on the website)
> 
> I can click on a line but the chart freezes. If i scroll, the line moves to the position of my cursor but i can't move it otherwise and can't place it down.

He propably hasn't updated the sample yet with the latest release. Check back later.

**Comment by Bellyang** [comment]
Is still not working on safari, i just updated lib at main branch.

**Comment by liihuu** [comment]
> Maybe you need to rebuild or directly reference.

**Comment by liihuu** [comment]
> It still not working on safari, i just updated lib at main branch.

Maybe you need to rebuild or directly reference.

**Comment by itzTheMeow** [comment]
v9.0.0 fixes this and the sample on the website now works properly
