### ISSUE TITLE
[BUG] Chart duplicating data.

### ISSUE THREAD

**Issue by itzTheMeow** [liihuu/KLineChart#387]
When zooming out and scrolling the chart (in firefox), the data is duplicated across the chart. Console logging the time returned from loadMore shows the time as the same for each call.
![image](https://user-images.githubusercontent.com/50887230/219506142-ce107a32-f98a-4e43-9279-2c893336fef8.png)

my code:
![image](https://user-images.githubusercontent.com/50887230/219506183-4c242652-01b3-47f8-b175-762bc6bf31f3.png)

Data returned: https://hastebin.com/share/etaxowiqor.json
this is a 1min interval

**Comment by itzTheMeow** [comment]
@liihuu is there a status on this? thanks

**Comment by liihuu** [comment]
The chart does not involve cycles, so you can render whatever data you give to the chart.

**Comment by itzTheMeow** [comment]
what do you mean? the `loadMore` function is running with the same timestamp each time causing it to duplicate data.

**Comment by EugeneMeles** [comment]
It looks like the server is response a non-empty array and **!!d.length** return true.

**Comment by itzTheMeow** [comment]
![image](https://user-images.githubusercontent.com/50887230/221372794-f177d03c-b888-4571-9f7b-46e18ac9bcbb.png)
it returns `true` telling it there's more data

**Comment by EugeneMeles** [comment]
Ahhh, OK.
Based on all of the above, `applyMoreData()` only push data in dataList(array) and not validation by timestamp.
You can check this manually, get "rendering" data from `const dataList = chart.getDataList();` and compare with the data received from the server.
