### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by soraly** [liihuu/KLineChart#392]
### 版本

9.1.0

### 复现步骤

一次性请求大量数据时，k线不连续了。可以往左拖拽的时候进行分页加载吗，或者用websocket

### 当前效果

<img width="1015" alt="企业微信20230309-175200@2x" src="https://user-images.githubusercontent.com/15606183/223985969-34702ac0-2761-4c87-9f12-01859c338792.png">

### 预期效果

一次性请求大量数据时，k线不连续了。可以往左拖拽的时候进行分页加载吗，或者用websocket

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by XYUU** [comment]
一次性请求大量数据时，k线不连续了。
**这是数据问题吧。**
可以往左拖拽的时候进行分页加载吗，或者用websocket。
**现在是显示最新的视口，历史行情需要从左往右拖拽，然后自动加载历史请求，文档中有写，多看文档。图表并不限制使用任何协议或方式加载数据。**

**Comment by soraly** [comment]
用了loadMore解决了，thanks

**Comment by ltp1024** [comment]
@soraly 左滑到最右如何判断何时加载下一页数据？
