### ISSUE TITLE
[Bug] 实例 API: zoomAtCoordinate文档与实际不符

### ISSUE THREAD

**Issue by yujiantao4616** [liihuu/KLineChart#396]
### 版本

9.1.1

### 复现步骤

实例 API: zoomAtCoordinate
文档上面的类型声明为 (scale: number, coordinate?: { x: number, y: number }, animationDuration?: number) => void
实际上coordinate这个参数为必传

### 当前效果

(scale: number, coordinate: { x: number, y: number }, animationDuration?: number) => void

### 预期效果

(scale: number, coordinate?: { x: number, y: number }, animationDuration?: number) => void

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
Fixed it.
