### ISSUE TITLE
安卓下手机qq浏览器会报错，无法运行给出的例子

### ISSUE THREAD

**Issue by ShowPenZ** [liihuu/KLineChart#40]
手机：小米mix2
系统: androd 9
浏览器：手机qq浏览器最新版本
运行库：此项目demo

以下是运行给出例子的bug
![221593658067_ pic](https://user-images.githubusercontent.com/25929987/86311283-9fa5ba00-bc52-11ea-8b7f-1dbba5d219c0.jpg)

又分别试了安卓下的其他机型上的手机qq浏览器发现皆会出现此状况，ios下的手机qq浏览器则不会出现此问题

**Comment by liihuu** [comment]
https://github.com/liihuu/KLineChart/issues/35#issuecomment-639397964

**Comment by ShowPenZ** [comment]
> [#35 (comment)](https://github.com/liihuu/KLineChart/issues/35#issuecomment-639397964)

![231593678396_ pic_hd](https://user-images.githubusercontent.com/25929987/86335266-dabee200-bc80-11ea-95b3-1527b8d74ebc.jpg)
有做兼容性处理
