### ISSUE TITLE
[Question] Show and edit trades in custom overlay

### ISSUE THREAD

**Issue by BTamas94** [liihuu/KLineChart#403]
I made a custom overlay based on the **"horizontalRayLine"** to show the open positions on the chart with 3 lines (price, SL, TP), and I can adjust the stops by dragging the lines. I get the positions from an API  and inject as points in overrideOverlay but there are some problems:

- points are not shown before i click somewhere on the chart
- I can’t deselect the trade line, the points remain on the line whatever i do
- the whole “Trade” overlay disappears if i want to draw a new line. 

This concept can work with overlays or do I need to use something else for this?

**Code snippet from the index.ts**
I extend the KLineChartsPro so my overlay is registered with the other overlays in the pro

```
import { init, registerOverlay } from 'klinecharts'
import trade from './trade'
import { Point } from 'klinecharts';

// initialize the chart
const chart = init(`app`)

// add data to the chart
chart?.applyNewData([
   { close: 4976.16, high: 4977.99, low: 4970.12, open: 4972.89, timestamp: 1587660000000, volume: 204 },
   { close: 4977.33, high: 4979.94, low: 4971.34, open: 4973.20, timestamp: 1587660060000, volume: 194 },
   { close: 4977.93, high: 4977.93, low: 4974.20, open: 4976.53, timestamp: 1587660120000, volume: 197 },
   { close: 4966.77, high: 4968.53, low: 4962.20, open: 4963.88, timestamp: 1587660180000, volume: 28 },
   { close: 4961.56, high: 4972.61, low: 4961.28, open: 4961.28, timestamp: 1587660240000, volume: 184 },
   { close: 4964.19, high: 4964.74, low: 4961.42, open: 4961.64, timestamp: 1587660300000, volume: 191 },
   { close: 4968.93, high: 4972.70, low: 4964.55, open: 4966.96, timestamp: 1587660360000, volume: 105 },
   { close: 4979.31, high: 4979.61, low: 4973.99, open: 4977.06, timestamp: 1587660420000, volume: 35 },
   { close: 4977.02, high: 4981.66, low: 4975.14, open: 4981.66, timestamp: 1587660480000, volume: 135 },
   { close: 4985.09, high: 4988.62, low: 4980.30, open: 4986.72, timestamp: 1587660540000, volume: 76 }
]);

registerOverlay(trade)

chart?.createOverlay("Trade");

const t = {
    id: 123456,
    type: "buy",
    volume: "0.01",
    price: 4968,
    sl: 4958,
    tp: 0,
    time: 1587660180000
  }


const points: Point[] = <Point[]> [{ value: t.price, timestamp: t.time },{ value: t.price, timestamp: t.time }]
chart?.overrideOverlay({ name: "Trade",  points: points})

```

**Trade.ts**

```
import { OverlayTemplate } from "klinecharts"

export interface TradeExtendData {
    id: number
    volume: number
    price: number
    type: string
    time: number
    sl: number
    tp: number
    vsl?: number
    vtp?: number
}

const trade: OverlayTemplate = {
    name: "Trade",
    totalStep: 3,
    needDefaultPointFigure: true,
    // needDefaultXAxisFigure: true,
    needDefaultYAxisFigure: true,
    createPointFigures: ({ coordinates, bounding }) => {
        return [
            {
                type: 'line',
                attrs: { coordinates: [{x: bounding.width, y: coordinates[0].y}, { x: 0, y: coordinates[0].y }] }
            }
        ]
    },
    performEventPressedMove: ({ points, performPoint, currentStep}) => {
        points[0].value = performPoint.value
        points[1].value = performPoint.value
        console.log(currentStep)
    },
    performEventMoveForDrawing: ({ currentStep, points, performPoint }) => {
        console.log(currentStep);
        if (currentStep === 2) {
        points[0].value = performPoint.value
        }
    },
    onMouseEnter: ((e) => {
        console.log(e); // Fired only once when i enter the chart
        return false
    })

}

export default trade
```

**UPDATE 1**
I tried without the pro, using the original example of creating and overriding a custom overlay, but the result is the same. For example if I create a second overlay with different name, only the last overlay is visible and can't be deselected.

**Comment by BTamas94** [comment]
Is there any update on this?

**Comment by liihuu** [comment]
Only on this overlay will the event respond.

Api `overrideOverlay`, if there is only name, all overlays with the same name will be overwritten.

**Comment by BTamas94** [comment]
Thank you for your response. I use separate names for the other overlay but the problem is the same with only one custom overlay. The example above is almost the same as the the example in the documentation but it doesn't work.

**Comment by liihuu** [comment]
Only on this overlay will the event respond.

Api `overrideOverlay`, if there is only name, all overlays with the same name will be overwritten.

**Comment by liihuu** [comment]
The two points in the example you provided are the same. You can try different timestamps or values.

**Comment by BTamas94** [comment]
I made a codesandbox example, maybe if you can take a look, this will describe my problem better
https://codesandbox.io/s/still-rgb-ys38uv

**Comment by liihuu** [comment]
Try version 9.1.2
