### ISSUE TITLE
[Bug] volume < 0时显示0

### ISSUE THREAD

**Issue by guotie** [liihuu/KLineChart#409]
### 版本

9

### 复现步骤

data的volume设置为0.1， 0.2等等

### 当前效果

如果volume >0 且volume < 1, 成交量图形上显示为0

### 预期效果

显示小数

### 环境

```markdown
- 系统: macOS
- 浏览器: Chrome
- 框架: React@18
```

**Comment by liihuu** [comment]
你可能需要设置下精度

**Comment by mawsyh** [comment]
> ### Version
> 
> 9
> ### Steps to reproduce
> 
> The volume of data is set to 0.1, 0.2, etc.
> ### current effect
> 
> If volume >0 and volume < 1, it will be displayed as 0 on the volume graph
> ### expected result
> 
> show decimals
> ### environment
> 
> ```gfm
> - 系统: macOS
> - 浏览器: Chrome
> - 框架: React@18
> ```
> 
> ### Supplementary Note
> 
> _No response _

check if this help you out https://github.com/liihuu/KLineChart/pull/412#issue-1666508744

**Comment by liihuu** [comment]
You must do like this,
```javascript
chart.createIndicator('VOL)
// Must be called after the api 'createIndicator'
chart.setPriceVolumePrecision(2, 1)
```
