### ISSUE TITLE
大神看你一直在更新项目，副图要能显示k线图才好

### ISSUE THREAD

**Issue by tangjiemian** [liihuu/KLineChart#41]
大神看你一直在更新项目，副图要能显示k线图才好

副图显示指标类型。要能设置显示K线。同一图中显示不同周期的K线这种需求很常见

**Comment by liihuu** [comment]
下个版本会添加。

**Comment by liihuu** [comment]
5.5.0已经发布，支持该功能。

**Comment by tangjiemian** [comment]
这真是一个好消息，您辛苦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lihu"<notifications@github.com&gt;; 
发送时间: 2020年7月26日(星期天) 晚上6:11
收件人: "liihuu/KLineChart"<KLineChart@noreply.github.com&gt;; 
抄送: "小飞船"<751585085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liihuu/KLineChart] 大神看你一直在更新项目，副图要能显示k线图才好 (#41)





 
5.5.0已经发布，支持该功能。
