### ISSUE TITLE
[Bug] applyNewData的参数为空数组时，不会更新k线

### ISSUE THREAD

**Issue by guotie** [liihuu/KLineChart#410]
### 版本

9.1.1

### 复现步骤

1. 当切换交易对后，如果新交易对的kline数组是空数组，这时不会更新k线图形。

### 当前效果

1. 当切换交易对后，如果新交易对的kline数组是空数组，不会更新k线图形。

### 预期效果

如果新交易对的kline数组为空数组，应该将k线图形清空

### 环境

```markdown
- 系统: macOS Monterey
- 浏览器: Chrome 102.0.5005.115
- 框架 React@18
```

**Comment by mawsyh** [comment]
by kline array do you mean the data that is being returned from "getHistoryKLineData" ? (I imagine you are using custom data here)

**Comment by guotie** [comment]
no.

when I switch pair,  i just use 
```
applyNewData([])
```
but the chart change nothing. and if i print `getDataList()`, it was []


If i use
```
applyNewData([{open:0, close:0, high: 0, low:0, volume: 0, turnover: 0, timestamp:0}])
```
then, old data was cleared.
