### ISSUE TITLE
[Feature] Solid Candle with Different Stroke Color

### ISSUE THREAD

**Issue by jinusean** [liihuu/KLineChart#416]
### Feature Description

Allow the preference to set different colors for candle's stroke and solid colors.

### To Do

New candle settings should be something like this...
```
candle: {
  type: 'candle_solid_stroke',
  bar: {
    upColor: 'white',
    upStrokeColor: 'black',
    downColor: 'black',
    downStrokeColor: 'black',
}
```

**Comment by mawsyh** [comment]
We already have the setting to set up and down colors [https://klinecharts.com/en-US/guide/styles.html](url)

maybe I didn't understand what is it you want here.

**Comment by liihuu** [comment]
Plan to add configurations for `upBorderColor`, `downBorderColor`, `noChangeBorderColor`, `upWickColor`, `downWickColor`, `noChangeWickColor`.
