### ISSUE TITLE
[Bug] 指标的回传参数 visibleRange.from 不准确

### ISSUE THREAD

**Issue by walkerxin** [liihuu/KLineChart#417]
### 版本

9.1.3 (9.0.0+版本都发现此问题)

### 复现步骤

1. 在指标的 draw 方法中打印 visibleRange.from
```TypeScript
draw: ({ ctx, indicator, visibleRange, defaultStyles }: any) => {
    console.log(visibleRange.from, visibleRange.to)
}
```
2. 拖动指标到 右边空缺，看打印日志

### 当前效果

![visibleRange.from不准确](https://user-images.githubusercontent.com/44486634/233120322-7565c6aa-66d2-4b14-9564-113bc2fbe2e5.jpg)

### 预期效果

如上图，获取到的 from 应该是 8045

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
v9.2.0
