### ISSUE TITLE
[Bug] onCandleBarClick not firing when clicking on candle wicks

### ISSUE THREAD

**Issue by jinusean** [liihuu/KLineChart#419]
### Version

9.2.0

### Steps to Reproduce

```
const chart - init('kline')
chart.subscribeAction(ActionType. onCandleBarClick, console.log)
```

### Current Behavior

Using function `subscribeAction(ActionType. onCandleBarClick, callback)`, callback is fired when I click on the candle bar's body, but does not fire when I click on the candle's wick.

### Expected Behavior

Callback should be fired even on wick clicks

### Environment

```markdown
- OS: OSX
- Browser: Chrome
- Framework: Vue
```

**Comment by liihuu** [comment]
It will trigger, but it doesn't seem very sensitive and needs optimization.
