### ISSUE TITLE
Price based indicator support

### ISSUE THREAD

**Issue by FlowerWrong** [liihuu/KLineChart#42]
for example [vpvr](https://www.tradingview.com/education/vpvr/)

**Comment by liihuu** [comment]
自定义技术指标可能能满足你的需求。

**Comment by FlowerWrong** [comment]
指标可以显示在Y轴吗？

**Comment by liihuu** [comment]
不太明白你的意思。具体可以加QQ群677936660

**Comment by liihuu** [comment]
v5.6.0  自定义指标新增render方法，可以自定义绘制
