### ISSUE TITLE
[Bug] v9 版 最高最低价显示问题（可能和可见范围的bug有关）

### ISSUE THREAD

**Issue by walkerxin** [liihuu/KLineChart#427]
### 版本

9.2.2

### 复现步骤

复现方法：滚动k线图到可见范围尾部缺省k线时（如图1），拖动最高价或最低价，离开可见范围内。

### 当前效果

![图1看到最高最低价](https://user-images.githubusercontent.com/20532096/237054305-b0e51a78-9229-4a53-925e-8a63b54437fc.png)

![最低价出了可见范围，没有对应变化](https://user-images.githubusercontent.com/20532096/237054282-7a50c80f-4cb9-4135-bc04-3e450a8e4ef4.png)

![最高最低价出了可见范围，没有对应变化](https://user-images.githubusercontent.com/20532096/237054269-6ffc121f-beb3-49c4-9dc2-ed27edc0b081.png)

### 预期效果

最高价 最低价 随着可见范围变化

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
没有8.6.4这个版本。不管什么版本，这个逻辑没有变过。
