### ISSUE TITLE
Get paneId in OverlayEvent

### ISSUE THREAD

**Issue by miccarrer** [liihuu/KLineChart#428]
Hello,

First of all, thanks for your great project, I enjoy a lot using it!

I would like to know if there is a way to get paneId when overlay is drawn (in OverlayEvent) ?

Here is sample code to illustrate my need:
```typescript
    function createOverlay (name: string): string|null {
      const overlay: OverlayCreate = {
        name,
        onDrawEnd: (ev: OverlayEvent) => {
          // which pane?
          return true
        }
      }
      return chart.createOverlay(overlay)
    }
```

Thanks in advance!

**Comment by liihuu** [comment]
v9.4.0
