### ISSUE TITLE
[Bug] chart zoom out, the candles on the chart are shown cut off

### ISSUE THREAD

**Issue by khakimme** [liihuu/KLineChart#434]
### Version

9.2.1

### Steps to Reproduce

In the old version 8..., this bug was not observed

### Current Behavior

<img width="847" alt="Screenshot 2023-05-26 at 12 27 17 PM" src="https://github.com/liihuu/KLineChart/assets/39030121/fbd266b0-f505-4994-8cc4-2a6a630b14b5">

### Expected Behavior

<img width="479" alt="Screenshot 2023-05-26 at 12 27 58 PM" src="https://github.com/liihuu/KLineChart/assets/39030121/f24068b7-1810-4b91-8bab-9b0fe5216e58">

### Environment

```markdown
- OS: macOS Monterey
- Browser: all
- Framework: React 18.2
```

**Comment by liihuu** [comment]
v9.4.0 fixed it.
