### ISSUE TITLE
[Bug] 在移动端左右滑动图表时，图表滑动动画未结束时再次手动滑动会导致图表卡顿

### ISSUE THREAD

**Issue by mercilessApple** [liihuu/KLineChart#435]
### 版本

9.3.0

### 复现步骤

在移动端使用图表，对图表进行x轴滑动，图表滚动动画未结束时手动再次滑动图表，会出现卡顿现象

### 当前效果

频繁滑动图表时，图表会卡顿闪现

### 预期效果

滑动动画未结束时再次滑动，应该不再卡顿

### 环境

```markdown
- 系统:window11
- 浏览器:谷歌浏览器
- 框架:vuejs
```

### 补充说明

无补充

**Comment by Vikanong** [comment]
同问题
