### ISSUE TITLE
5.5支持副图k线，不知道怎么使用

### ISSUE THREAD

**Issue by tangjiemian** [liihuu/KLineChart#44]
5.5支持副图k线，不知道怎么使用。

**Comment by liihuu** [comment]
内置的技术指标，只有MA, BOLL, SAR, EMA支持

**Comment by tangjiemian** [comment]
通过自定义 bar 类型的指标实现吗  这个bar不会弄K线的high low线

**Comment by liihuu** [comment]
自定义技术指标，shouldOhlc设置成true就行

**Comment by tangjiemian** [comment]
@liihuu 哥，没弄成功。求更新个demo

**Comment by liihuu** [comment]
https://github.com/liihuu/TechnicalIndicator  自定义技术指标可以仿照这个写
https://github.com/liihuu/KLineChartSample  示例代码
另外可以加QQ讨论群677936660
