### ISSUE TITLE
[Feature] setVisibleRange

### ISSUE THREAD

**Issue by oneart-dev** [liihuu/KLineChart#441]
### Feature Description

It would be super helpful to add function setVisibleRange(start, end). 

I'm showing entry and exits on the chart and i would like to be able to focus exact range(trade) so user don't have to scroll every time.

### To Do

1. add setVisibleRange function

**Comment by oneart-dev** [comment]
Find the solution for now:
```javascript
    const { from, to } = range();
    const bars = (to - from) / interval.IntervalMs;  
    const chartWidth = this.getChartWidth(); // use clientWidth to get chart width if responsive or fixed value
    const barSpace = chartWidth / bars;
    this.i.setBarSpace(Math.max(Math.min(barSpace, 50), 1)); // respect constraints
    this.i.scrollToTimestamp(lastOrderTimestamp);
```

If you using markers timestamp it is good idea to add padding on both sides so it looks nice

**Comment by rascaler** [comment]
that's great, I will have a try

**Comment by liihuu** [comment]
#430
