### ISSUE TITLE
[Bug] too small area for resizing pane click activation

### ISSUE THREAD

**Issue by oneart-dev** [liihuu/KLineChart#444]
### Version

9.4.0

### Steps to Reproduce

1. Open https://preview.klinecharts.com/#en-US
2. Try resize pane by moving mouse from top to bottom

### Current Behavior

First you see cursor changing state to resize but pane border do not highlighting
If you move cursor lower everything works correct

### Expected Behavior

Cursor changing action and border highlighting should happen at the same time and area should be bigger.

### Environment

```markdown
- OS: Macos ventura 13.4
- Browser: Chrome 113
- Framework: Not relevant
```

### Any additional comments?

https://github.com/liihuu/KLineChart/assets/70148117/d5ef2459-1d21-402a-937e-69d839a54924

**Comment by oneart-dev** [comment]
@liihuu the issue present in a new version

https://github.com/liihuu/KLineChart/assets/70148117/0c3c352f-c08e-4168-bd86-fa2e640b8cad

**Comment by liihuu** [comment]
Maybe the code needs to be rolled back
