### ISSUE TITLE
[Bug] Unhandled Runtime Error: v.text.match is not a function

### ISSUE THREAD

**Issue by khakimme** [liihuu/KLineChart#449]
### Version

9.4

### Steps to Reproduce

When opening the chart, such a tank began to appear

### Current Behavior

<img width="765" alt="Screenshot 2023-06-16 at 10 39 20 AM" src="https://github.com/liihuu/KLineChart/assets/39030121/a55fb206-eac7-4423-91e9-f61d4467dd79">

### Expected Behavior

...

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 103
- Framework: React@18
```

**Comment by liihuu** [comment]
Provide the style configuration.
