### ISSUE TITLE
[Bug] checkCoordinateOnRect for 1px figure

### ISSUE THREAD

**Issue by oneart-dev** [liihuu/KLineChart#451]
### Version

9.5.0

### Steps to Reproduce

1. Open PRO chart
2. Add rectangle on the chart with no height or width.
3. Try to select it

### Current Behavior

https://github.com/liihuu/KLineChart/assets/70148117/e32dd87d-aca0-4d0c-961f-5c139ec93327

### Expected Behavior

Overlay should be selectable for this i recommend add to checkCoordinateOnRect condition like:
```js
export function checkCoordinateOnRect (coordinate: Coordinate, rect: RectAttrs): boolean {
 const height = Math.max(rect.width, 5)
 const width = Math.max(ect.height, 5)
  return (
    coordinate.x >= rect.x &&
    coordinate.x <= rect.x + width &&
    coordinate.y >= rect.y &&
    coordinate.y <= rect.y + height
  )
}
```

### Environment

```markdown
- OS: Macos
- Browser: Chrome
- Framework: net related
```

**Comment by oneart-dev** [comment]
Width and height probably can be negative, for this case:
```js
export function checkCoordinateOnRect (coordinate: Coordinate, rect: RectAttrs): boolean {
 const minSize = 5;
 const height = Math.abs(rect.height) < minSize ? minSize : rect.height;
 const width = Math.abs(rect.width) < minSize ? minSize : rect.width;
  return (
    coordinate.x >= rect.x &&
    coordinate.x <= rect.x + width &&
    coordinate.y >= rect.y &&
    coordinate.y <= rect.y + height
  )
}
```

**Comment by liihuu** [comment]
Welcome to PR

**Comment by oneart-dev** [comment]
I will try to implement it. As we both using high DPI macbooks for testing we can use this method to simulate low dpi monitors, it works pretty well: https://stackoverflow.com/questions/57606558/is-there-a-way-to-simulate-low-dpi-rendering-in-chrome-or-firefox
