### ISSUE TITLE
[Feature] Subscribe to overlay data change

### ISSUE THREAD

**Issue by r0kan** [liihuu/KLineChart#460]
### Feature Description

Hi. I would like to be able to track changes in the drawn layers and save them locally (localStorate, API, ...etc)
Maybe there is already such a possibility, but I did not find it in the documentation

### To Do

1. chart.subscribeAction('OnOverlayChange', (overlay) => {})

**Comment by oneart-dev** [comment]
Listen for onDrawEnd and onPressedMoveEnd for each created overlay. 

```js
chart.createOverlay({
    name: "Segment",
    onDrawEnd({ overlay }): boolean => {
        this.onOverlayChange();
        return true;
    },
    onPressedMoveEnd({ overlay }): boolean => {
        this.onOverlayChange();
        return true;
    },
})
```

**Comment by oneart-dev** [comment]
But be aware of this issue, as restoring overlay state can lead to bugs https://github.com/liihuu/KLineChart/issues/459
