### ISSUE TITLE
can hidden or remove the indicator tooltip?

### ISSUE THREAD

**Issue by tingshuai** [liihuu/KLineChart#467]
### Feature Description

**for example:**
![1](https://github.com/liihuu/KLineChart/assets/23158246/65ad61c1-143c-4243-814b-b8cc9c7584a9)     ![2](https://github.com/liihuu/KLineChart/assets/23158246/75fc4305-7da1-4db2-8588-24f0f86fb87c)
I have removed tooltip(UP, MID, DN) in the boll indicator;  but how to remove the tooltip "BOLL(20,2)" which I highlighted in picture 1;

### To Do

1. relate tooltip

**Comment by liihuu** [comment]
In styles, `indicator.tooltip.showName: false`

**Comment by tingshuai** [comment]
> In styles, `indicator.tooltip.showName: false`

i got it, i should config it in init func options... and it did work. You solved my problem ;thanks; 
but it worked in all the indicators; it seems that it should also be configurable in [overrideIndicator](https://klinecharts.com/guide/instance-api.html#overrideindicator-override-paneid-callback), then it won't affect other indicators。

**Comment by QGB** [comment]
How to temporary hide a indicator,  like tradingview  
![image](https://github.com/liihuu/KLineChart/assets/8005654/4d0e8e9c-bcf1-4db5-af63-b869662644b0)

**Comment by QGB** [comment]
```
b=chart._chartStore.getIndicatorStore()._instances.get("candle_pane").get('BOLL')

b.setVisible(false)
true
b.setVisible(false)
false
```
为什么这个不会自动刷新，需要手动缩放图表，指标才会消失？
