### ISSUE TITLE
[Feature] 存储用户上次绘制的图形

### ISSUE THREAD

**Issue by cloderW** [liihuu/KLineChart#468]
### 需求描述

目前用户自己通过画图工具进行画的各种线，当用户重新加载图表， 这些线就没有了，使用起来很不方便，是否可以按TradingView一样存储上次用户画的线

### 具体实现

把已经划好的线存储，当用户重新加载时，画好的线可以继续展示，不被清空，只有当用户主动清除的时候才会取消显示。

**Comment by Basttyy** [comment]
@cloderW do can you share how you solved this? for the sake of others. thanks
