### ISSUE TITLE
Change number size

### ISSUE THREAD

**Issue by mrs4z** [liihuu/KLineChart#470]
Good day! Can you tell me how to change the display of text in this area?

<img width="1145" alt="Screenshot 2023-08-08 at 17 37 47" src="https://github.com/liihuu/KLineChart/assets/49597416/018607fe-6d75-4536-a540-451eb80f0671">

Due to the fact that it cuts, the graph seems small, how to fix it?

**Comment by liihuu** [comment]
https://klinecharts.com/en-US/guide/faq.html#the-candle-shows-a-line-no-fluctuation-what-to-do

```js
setPriceVolumePrecision
```
