### ISSUE TITLE
[Feature] yAxis支持数组形式

### ISSUE THREAD

**Issue by qbwebfrontend** [liihuu/KLineChart#474]
### 需求描述

需要显示两条Y轴

### yAxis 支持数组形式，
setStyles({
  yAxis: [{
   ...,
   index: 0  // 每条Y轴有序列号
  }]
})

### 期望场景：同时显示百分数轴和数值轴，如下图
![image](https://github.com/liihuu/KLineChart/assets/96709915/0637604e-a189-45d7-a88b-7592640dcf16)

**Comment by qbwebfrontend** [comment]
![image](https://github.com/liihuu/KLineChart/assets/96709915/18753796-9ba4-4527-b9d4-2bb51e106532)

**Comment by liihuu** [comment]
#348
