### ISSUE TITLE
[Feature] 建议增加区间选取功能

### ISSUE THREAD

**Issue by yunTerry** [liihuu/KLineChart#501]
### 需求描述

很棒开源库，非常好用，不过目前好像没有区间选取的功能，希望能通过鼠标拖动选取一段K线图，返回这段区间内的行情数据（或者起始点索引），类似于这种：
![select](https://github.com/liihuu/KLineChart/assets/15991012/8f458aa2-9634-4c8a-978f-0972f92bd500)
这样方便计算一段区间内涨跌幅、换手率、最大回撤等信息

### 具体实现

1. 拖动鼠标选取一段K线图
2. 监听并返回区间内的行情数据
3. 可以调整区间大小或左右移动区间

**Comment by liihuu** [comment]
自己实现一个自定义覆盖物即可
