### ISSUE TITLE
[Feature] 建议在X轴底部增加缩略划动条

### ISSUE THREAD

**Issue by yunTerry** [liihuu/KLineChart#503]
### 需求描述

有十几年的行情数据，想要快速查看某一年不太方便，拖动麻烦

### 具体实现

可以在底部增加一个缩略划动条，类似echarts底部的 slider bar：
![slider](https://github.com/liihuu/KLineChart/assets/15991012/0b5d9e71-0f3e-4f42-806e-4e0d587c0af7)
这样方便快速调整查看区间

**Comment by liihuu** [comment]
可以根据api 自己做一个
