### ISSUE TITLE
蜡烛两头的最高价最低价的线刚初始化看起来会有点粗而且有些模糊，跟蜡烛颜色也有点不一样，像设置了透明度，滚动鼠标缩放就会正常，demo里面的也存在这种问题，能设置吗

### ISSUE THREAD

**Issue by JJMariah** [liihuu/KLineChart#51]

**Comment by JJMariah** [comment]
![image](https://user-images.githubusercontent.com/30403748/92688886-b5311180-f370-11ea-8f77-16227c495f52.png)

**Comment by liihuu** [comment]
应该是柱子和影线的宽度不一致，引起的颜色视觉误差
