### ISSUE TITLE
y轴在内部，浮动框显示， 文字被浮动框遮住，怎么解决？

### ISSUE THREAD

**Issue by clerkzhang** [liihuu/KLineChart#52]
让Y轴的文字限制在最低层。 chart图也被Y轴文字覆盖了。

[
<img width="396" alt="截屏2020-09-25 下午5 38 12" src="https://user-images.githubusercontent.com/892608/94252170-23bbc500-ff56-11ea-9e5b-5451a473cac5.png">
](url)

**Comment by liihuu** [comment]
就是这样设计的，y轴在最顶层。
