### ISSUE TITLE
Minus value on Crosshair Coordinate Y of Volume Technical Indicator

### ISSUE THREAD

**Issue by dickyindra** [liihuu/KLineChart#58]
Why is there a minus value on Crosshair Coordinate Y of Volume Technical Indicator?

<img width="411" alt="Screen Shot 2020-12-10 at 13 42 27" src="https://user-images.githubusercontent.com/13186704/101731168-cfa09580-3aed-11eb-9e6b-911c793f642a.png">

I added a custom technical indicator for volume.
```
kLineChart.addCustomTechnicalIndicator({
    name: "VOL",
    series: "volume",
    shouldFormatBigNumber: true,
    plots: [{
        key: "volume",
        type: "bar",
        color: function(data, options) {
            const kLineData = data.currentData.kLineData || {}
            if (kLineData.close < kLineData.open) {
                return options.bar.downColor
            }
            return options.bar.upColor
        }
    }],
    calcTechnicalIndicator: function(dataList) {
        return dataList.map((kLineData) => {
            return {
                volume: kLineData.volume
            }
        })
    },
    precision: 4
})
```

**Comment by liihuu** [comment]
Try it 
```
kLineChart.addCustomTechnicalIndicator({
    ...........
    ...........

    baseValue: 0,
    minValue: 0
})
```

**Comment by liihuu** [comment]
Try it 
```
kLineChart.addCustomTechnicalIndicator({
    ...........
    ...........

    baseValue: 0,
    minValue: 0
})
```

**Comment by dickyindra** [comment]
There is still a minus value, and the volume bar is untidy.

<img width="421" alt="Screen Shot 2020-12-10 at 17 25 13" src="https://user-images.githubusercontent.com/13186704/101760015-e60a1980-3b0c-11eb-9e9f-e830cb857d69.png">

**Comment by liihuu** [comment]
The graph drawing will leave some gaps up and down, so when the minimum value is 0, there will be a minus value, I think it has no effect. The bars are not aligned and will be optimized later.

**Comment by dickyindra** [comment]
But according to UX (User Experience) that is so bad.
Okey, thank you.

**Comment by liihuu** [comment]
If you are still using it, you can try version 6.0.3, which adds the configuration `candle.margin` and `technicalIndicator.margin`, but currently it does not support setting for a single technical indicator.

**Comment by liihuu** [comment]
If you are still using it, you can try the latest version, which adds the configuration `candle.margin` and `technicalIndicator.margin`, but currently it does not support setting for a single technical indicator.
