### ISSUE TITLE
[Bug] 'addCustomTechnicalIndicator', which lacks return-type annotation, implicitly has an 'any' return type.

### ISSUE THREAD

**Issue by 90arther** [liihuu/KLineChart#60]
<img width="1019" alt="Screen Shot 2020-12-30 at 15 56 38" src="https://user-images.githubusercontent.com/3853101/103337964-d2bcef00-4ab7-11eb-8909-497d18f30186.png">

你好，这里似乎缺少了返回类型声明

Version: typescript 3.5.3, tslint 5.20.1

**Comment by 90arther** [comment]
@liihuu Hi, Could you release for this issue? Thanks

**Comment by liihuu** [comment]
这个问题的修复将和下个版本新功能一起发布，可以先临时修改node_modules/klinecharts/types/index.d.ts。
