### ISSUE TITLE
Draw Buy/Sell point

### ISSUE THREAD

**Issue by davidPardoC** [liihuu/KLineChart#67]
Hi, first off all awesome job, is even better than Highcharts Stock to be honest.
I have a few questions about the library.
1) Is there a way to get the data of a candle e.g : The position in the charts (x,y)
2) Im using websockets to update the chart data , Im trying to draw buy sell points using websockets as well , im using  **subscribeDrawAction**,  im usign the timestamp to compare and draw de mark, but only works the firts time the candle renderize , y think something is happening whit the updateData method , i think because is replacing the timestamp. 
I'll be very thankfull if you can clarify this doubts. 
Thank you

**Comment by liihuu** [comment]
1. There is currently no way to get the position on the chart, i am considering adding.
2. 
```js
chart.subscribeDrawAction('drawCandle', ({ ctx, dataIndex, kLineData, coordinate, isCandle }) => {
     // do something
     // Here it will be triggered as long as the candle is rendered

     console.log(dataIndex, kLineData)
})
```

Hope it helps you.
