### ISSUE TITLE
Display on mobile

### ISSUE THREAD

**Issue by gasnani1** [liihuu/KLineChart#70]
Hi,  thanks for your effort.  The project is excellent.

I tried https://liihuu.github.io/KLineChart/ on mobile but it is not sized accordingly eg. cannot see the price axis etc.

How do I use KLineChart on mobile for proper display?   Thanks!

**Comment by liihuu** [comment]
https://liihuu.github.io/KLineChart/ is just a sample page, it simply showing some features of the chart, ignoring the display on the mobile device, thank you for your suggestion, I will consider this issue, the chart itself is supported mobile.
