### ISSUE TITLE
Use as strategy backtest viewer

### ISSUE THREAD

**Issue by smolleyes** [liihuu/KLineChart#72]
Hi!

First thanks for this great great lib 🤘!! Awesome

I m building a trading bot and want to use your lib as a strategy backtest viewer... So is there a way to get data from candles and associated indicators then draw a buy/sell tooltip on top of the candle? Could be nice to get values of all candles and associated indicators before rendering maybe then add something to draw this tooltip when conditions are ok...? Sorry for my english

Thanks again!👏👏

**Comment by liihuu** [comment]
You can try the instance method `subscribeDrawAction`.

**Comment by smolleyes** [comment]
Hi! Ok thanks it s working 🤘
