### ISSUE TITLE
bugfix:  utils.number.binarySearchNearest

### ISSUE THREAD

**Issue by lofreer** [liihuu/KLineChart#74]
`/**
 * 二分查找最接近的数
 * @param dataList
 * @param valueKey
 * @param targetNumber
 * @return {number}
 */
export function binarySearchNearest (dataList, valueKey, targetNumber) {
  let midIndex
  let left = 0
  let right = dataList.length - 1

  // 保证指针最终停留在相邻的两个数,所以这里是判断是否大于1
  while (right - left > 1) {
    midIndex = Math.floor((left + right) / 2)
    // 相同值匹配
    const midValue = dataList[midIndex][valueKey]
    if (targetNumber === midValue) {
      return midIndex
    }
    // 如果目标数比中间小，所以范围在左边
    if (targetNumber < midValue) {
      right = midIndex
    } else {
      left = midIndex
    }
  }
  // 最后比较这两个数字的绝对差大小即可。
  return Math.abs(targetNumber - dataList[left][valueKey]) <= Math.abs(targetNumber - dataList[right][valueKey]) ? left : right;
}`

**Comment by liihuu** [comment]
看这个commit，[dbb5d46a241eeec2c95c4a53032675c880f6445c](https://github.com/liihuu/KLineChart/commit/dbb5d46a241eeec2c95c4a53032675c880f6445c)
