### ISSUE TITLE
bugfix: data.base.mark.GraphicMark._drawPolygons

### ISSUE THREAD

**Issue by lofreer** [liihuu/KLineChart#75]
`
/**
   * 绘制多边形
   * @param ctx
   * @param polygons
   * @param style
   * @param markOptions
   * @private
   */
  _drawPolygons (ctx, polygons, style, markOptions) {
    ctx.save()
    let fillStroke
    if (style === GraphicMarkDrawStyle.FILL) {
      ctx.fillStyle = markOptions.polygon.fill.color
      fillStroke = ctx.fill
    } else {
      ctx.lineWidth = markOptions.polygon.stroke.size
      ctx.strokeStyle = markOptions.polygon.stroke.color
      fillStroke = ctx.stroke
    }
    if (polygons.length > 0) {
      renderLine(ctx, () => {
        ctx.beginPath()
        ctx.moveTo(polygons[0].x, polygons[0].y)
        for (let i = 1; i < polygons.length; i++) {
          ctx.lineTo(polygons[i].x, polygons[i].y)
        }
        ctx.closePath()
        fillStroke.call(ctx)
      })
    }
    ctx.restore()
  }
`

**Comment by liihuu** [comment]
[3476105c3c0b73119b4dec470df8af7125be2a48](https://github.com/liihuu/KLineChart/commit/3476105c3c0b73119b4dec470df8af7125be2a48) 这个commit修改过了。

**Comment by lofreer** [comment]
前面没留意看你的代码，就是你新的修改有问题，或者是polygons这个参数传值有问题，polygons的子元素已经不是数组了，你可以画个rect图形试试看。

**Comment by lofreer** [comment]
前面没留意看你的代码，就是你新的修改有问题，或者是polygons这个参数传值有问题，polygons的子元素已经不是数组了，你可以画个rect图形试试看。

**Comment by liihuu** [comment]
多边形也修改成了和线一样，可以有多个，二维数组
