### ISSUE TITLE
Bounty issue label

### ISSUE THREAD

**Issue by JakeAdler** [liihuu/KLineChart#76]
Thanks for creating this awesome library! This is the most flexible and extensible solution that I could find so I'm planning on integrating into a project of mine. There are a couple features that I would really like to see implemented, however I don't have the time to dive too deeply into the internals of this project. I'd be willing to put a bounty on some of those features, would you be open to adding a `Bounty` label so that myself and any other users of this library can put extra steam behind the features we'd like to see implemented most?

There are projects like https://www.bountysource.com/ which can make the process a bit easier.

**Comment by liihuu** [comment]
Thank you very much, the community will further improve.

**Comment by fuzzthink** [comment]
@JakeAdler Thank you for starting this. @liihuu Once you add a `Bounty` label, it will make them standout more and I believe we will see more people joining to help out.
