### ISSUE TITLE
Update only last candle

### ISSUE THREAD

**Issue by smolleyes** [liihuu/KLineChart#78]
Hi

Do you have an exemple on how to update only the last candle lile in ypur demo but keep the selected timeframe..😅?

I receive updates thru websockets but if i use updateDatas the chart update every second :/ i m on 15min and want to stay on my selected timeframe
Just update the last candle value and get the new candle of we are on a new 15 min... (Sorry for my english hatd to explain 🤘) thanks!

**Comment by smolleyes** [comment]
Got it working now but not with updateData since it check the timestamp 😕 

Works with applyNewData but it reload everytime i think maybe somethong to do here no? ( or i do it bad)

**Comment by liihuu** [comment]
If the data pushed by websocket is not a standard cycle timestamp, you need to write some logic to format it yourself.

**Comment by smolleyes** [comment]
Hi!

I reformat it no problem but the timestamp is the same as previously i have
the updates on my candle working my only problem now is it focus on the
last candle at each update 😅

**Comment by smolleyes** [comment]
hi

ok don t know maybe i m stupid but can t get it working...

if you have time to post an exemple on how you update Just the last candle (when new price coming from websocket) it might be very very cool :) sorry to bother you !

love your lib! just this small thing

**Comment by smolleyes** [comment]
hello

humm finally it s "working" but i see the change on the candle only if i zoom/unzoom the chart  :/ searching why ...
