### ISSUE TITLE
Access indicators values 

### ISSUE THREAD

**Issue by smolleyes** [liihuu/KLineChart#80]
Hi! 

Can t find a way to get the indicator values 😅 is there a method for that please?

Thanks

**Comment by liihuu** [comment]
`getTechnicalIndicatorInfo`

**Comment by danielmalencar** [comment]
You did it?
For me it only returns:
{name: "MA", series: "price", calcParams: Array (1), precision: 4, styles: {…}}

**Comment by smolleyes** [comment]
> You did it?
> For me it only returns:
> {name: "MA", series: "price", calcParams: Array (1), precision: 4, styles: {…}}

No sorry ... Finally I made my own api with all talib and tulind indicators running on node then override indicators in klinechart with the values.. maybe i ll share it later could be  nice if we can get a big indicator bank for this lib with custom calcparams etc etc🤘

**Comment by danielmalencar** [comment]
the only way I managed to get to the value was this

chart._chartPane._candlePane._technicalIndicators[0].result[chart._chartPane._candlePane._technicalIndicators[0].result.length-1]

**Comment by QQQult** [comment]
> No sorry ... Finally I made my own api with all talib and tulind indicators running on node then override indicators in klinechart with the values.. maybe i ll share it later could be nice if we can get a big indicator bank for this lib with custom calcparams etc etc

sounds fantastic, it's be awesome if you shared your implementation

**Comment by danielmalencar** [comment]
> the only way I managed to get to the value was this
> 
> chart._chartPane._candlePane._technicalIndicators[0].result[chart._chartPane._candlePane._technicalIndicators[0].result.length-1]

Where 0 is the index of the indicator in the indicator array

**Comment by smolleyes** [comment]
> > No sorry ... Finally I made my own api with all talib and tulind indicators running on node then override indicators in klinechart with the values.. maybe i ll share it later could be nice if we can get a big indicator bank for this lib with custom calcparams etc etc
> 
> sounds fantastic, it's be awesome if you shared your implementation

I will 😅 my goal is to make a graphql api just by asking ticker/timeframe/array of indicators with calcparams for each... This lib is very nice to draw the indicators but need a way to change the calcparms more easily... Actually we have to override the whole indicator just for that... :( Very very nice lib but support/replies are not as good (sorry to say that but just the truth).

**Comment by liihuu** [comment]
The future version of `getTechnicalIndicatorByPaneId` will return the calculation results of technical indicators.

**Comment by liihuu** [comment]
Version 7.0.1 `getTechnicalIndicatorByPaneId` has returned results.
