### ISSUE TITLE
[Bounty] Add annotation functionality

### ISSUE THREAD

**Issue by JakeAdler** [liihuu/KLineChart#81]
This relates to, but intends to be a more in depth discussion of other issues (#67)
The current solution for this is to use `chart.subscribeDrawAction`, which has a couple of drawbacks.

- In order to remove or update annotations drawn with `subscribeDrawAction`, you must clear the entire chart since there is no way to access the annotations exclusively. This also makes the `updateData` method useless, since the entire chart must be torn down to remove stale annotations.
- This method runs each time a candle is drawn, on a chart with thousands of candles with tens of annotations, this can become highly inefficient and creates redundant looking code. 

Suggestions:

```js
chart.drawAnnotations([
  {
    timestamp: 1,
    position: "above",
    style: {...},
    tooltip: {...} // This would be awesome!
  },
  {
    timestamp: 2,
    position: "below",
    style: {...},
  },
]);
chart.updateAnnotations([...]);
chart.clearAnnotations();
```

**Comment by JakeAdler** [comment]
I've placed a $50 USD bounty on this issue (#76)
https://www.bountysource.com/issues/96463000-add-annotation-functionality

**Comment by liihuu** [comment]
This is a good suggestion.

**Comment by JakeAdler** [comment]
@liihuu Are there any significant blockers to implementing this feature? Or is it already being worked on? Just wasn't sure from you're response whether or not something like this would make its way into the project soon.

**Comment by liihuu** [comment]
I need more time outside of work, so the update progress is a bit slow. I hope to understand.

Thanks again for following this library.

**Comment by liihuu** [comment]
Version 7.1.0 has been supported.

**Comment by JakeAdler** [comment]
@liihuu This looks great! 

Small issue:

From `instance-api.md`
```
chart.createAnnotation({
..
  styles: { ... }
...
})
```

should be 
```
chart.createAnnotation({
..
  styles: { symbol: {...} }
...
})
```

In the actual in the `Annotation` class ([here](https://github.com/liihuu/KLineChart/blob/89c6b7a1e1b1f06f52f0d578c8342605319c978c/src/data/base/overlay/annotation/Annotation.js#L55), [here](https://github.com/liihuu/KLineChart/blob/89c6b7a1e1b1f06f52f0d578c8342605319c978c/src/data/base/overlay/annotation/Annotation.js#L129), and [here](https://github.com/liihuu/KLineChart/blob/89c6b7a1e1b1f06f52f0d578c8342605319c978c/src/data/base/overlay/annotation/Annotation.js#L185)), we look for `styles.symbol` (which **is** what is documented in `styles.md`).  We could just update the docs, but the `symbol` property seems kind of useless in the first place, since there are no other properties on the object, unless there are plans to add other properties, what do you think @liihuu ?

Thanks for this addition, I know you're busy and I appreciate your effort! Also @liihuu click on the bounty link and click on "SOLVE ISSUE" so that you can claim this bounty when we close this issue :moneybag:

**Comment by liihuu** [comment]
Yes, there are some problems with the documentation, I have updated it. Thank you for your sponsorship.

**Comment by JakeAdler** [comment]
Thanks a lot @liihuu

**Comment by JakeAdler** [comment]
Make sure that you claim your bounty on [Bountysource](https://www.bountysource.com/issues/96463000-bounty-add-annotation-functionality)!
