### ISSUE TITLE
[Proposal] Project structure change

### ISSUE THREAD

**Issue by JakeAdler** [liihuu/KLineChart#87]
I think that the current monolithic structure of the project will not scale well in the future. I think there are a few structural changes that should be made while the project is still fairly small.

- Move to a github orginization
- Break out modular packages from the monolith
- Move to a monorepo or multi-repo structure 

This will make it much easier for people to work on certain portions of the project, rather than having to reason about how all the pieces integrate together.

**Comment by liihuu** [comment]
Thank you so much for your suggestion.

**Comment by liihuu** [comment]
@JakeAdler Thank you so much for your suggestion.
