### ISSUE TITLE
父容器无法滚动

### ISSUE THREAD

**Issue by liaomingsen** [liihuu/KLineChart#90]
你好，我把K线图放到一个可以滚动的容器中，当我把鼠标放到K线图中，并设置setZoomEnabled(false)，鼠标滚轮滚动后父容器无法上下滚动。

建议当setZoomEnabled(false)后，父容器可以上下滚动。

this._target.addEventListener('wheel', boundMouseWheelHandler, {
  passive: !this._zoomEnabled // 此处修改
});

**Comment by liihuu** [comment]
v8.2.0 已经优化了此问题
