### ISSUE TITLE
getTechnicalIndicatorByName("MA")  Does not return the value, only properties

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#91]
For me it only returns:
{name: "MA", series: "price", calcParams: Array (1), precision: 4, styles: {…}}

But I wanted to get the current price of the indicator

**Comment by danielmalencar** [comment]
the only way I managed to get to the value was this

chart._chartPane._candlePane._technicalIndicators[0].result[chart._chartPane._candlePane._technicalIndicators[0].result.length-1]

**Comment by liihuu** [comment]
The latest version is already supported.
