### ISSUE TITLE
To select a graphic mark programmatically

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#94]
Is it possible to select a graphic mark programmatically? How?

**Comment by liihuu** [comment]
`createGraphicMark(name, options)`
You can refer to [GraphicMark.d.ts CreateGraphicMarkOptions](https://github1s.com/liihuu/KLineChart/blob/HEAD/types/GraphicMark.d.ts)
```js
export declare interface CreateGraphicMarkOptions {
  id?: string;
  points?: TimestampPricePoint[];
  styles?: any;
  onDrawStart?: (event: GraphicMarkEvent) => void;
  onDrawing?: (event: GraphicMarkEvent) => void;
  onDrawEnd?: (event: GraphicMarkEvent) => void;
  onClick?: (event: GraphicMarkEvent) => void;
  onRightClick?: (event: GraphicMarkEvent) => boolean;
  onPressedMove?: (event: GraphicMarkEvent) => void;
  onRemove?: (event: GraphicMarkEvent) => void;
}
```

**Comment by danielmalencar** [comment]
I don't think you understood me.
It means selecting a Graphic Mark already created.

**Comment by liihuu** [comment]
Need to operate the selected graphic mark?

**Comment by danielmalencar** [comment]
I already have Graphic Marks created. Now I need to activate a specific one, like the user click, however, programmatically.
Sorry for my horrible English

**Comment by liihuu** [comment]
Try it,
```js
chart.createGraphicMark('segment', {
    onClick: function (event) { console.log(event) }
})
```
Click on the created segment to see if there is a log print.

**Comment by danielmalencar** [comment]
Yes, but it hasn't helped me yet:
![image](https://user-images.githubusercontent.com/25048796/112706030-56506700-8e80-11eb-862f-a5db222ebd1a.png)

**Comment by liihuu** [comment]
At least tell me what function you want to implement so that I can help you solve the problem.

**Comment by danielmalencar** [comment]
chart.setActive(graphMarkID)
