### ISSUE TITLE
priceToPoint(price)   function

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#95]
I have a suggestion that can be useful for many people, the **priceToPoint (price**) function that **returns the x and y coordinates on the chart**. This will allow you to make price markings programmatically.

//Return X,Y coordinates on graphic (considering zoom level and scroll)
**priceToPoint(price)**

**Comment by danielmalencar** [comment]
sorry, r**eturn y position of the price**

**Comment by danielmalencar** [comment]
I'm anxious

**Comment by liihuu** [comment]
@danielmalencar I don’t have much free time to deal with lib recently, but I will release a new version as soon as possible.

**Comment by liihuu** [comment]
Api `convertToPixel` and `convertFromPixel` have been added to version 7.1.0.
