### ISSUE TITLE
Zoom scroll zooms too much, bars disappears

### ISSUE THREAD

**Issue by fuzzthink** [liihuu/KLineChart#97]
When I zoom-in scroll too much, bars disappears. Bars do appear again when I zoom scroll back out.

I don't see this issue running the Sample repo, but it does happen in my code. I want to see if anyone has either ran across this or know what causes it before trying to simplify my code to a fiddle. 

EDIT: It happens when bars are daily bars. When I use intraday bars, the zoom scroll locks correctly. Since all demos are intraday bars, maybe that's why I'm not seeing it there. Changing bars to daily bars in https://liihuu.github.io/KLineChart/ does lock the zoom scroll correctly however.

thanks.

**Comment by fuzzthink** [comment]
Found issue!  Data had some bars with only close and "NaN" for ohl. Mapping the following code fixes it. Should this library include this so users won't waste time debugging?

```javascript
const eqNaN = (n=0) => isNaN(n) || n==='NaN'
const ohlcv = ({ open, high, low, close, volume }) => ({
  open: eqNaN(open) ? close: open,
  high: eqNaN(high) ? close: high,
  low: eqNaN(low) ? close: low,
  close,
  volume: volume || 0,
})
```

**Comment by danielmalencar** [comment]
> Found issue! Data had some bars with only close and "NaN" for ohl. Mapping the following code fixes it. I think this library should prevent bars disappearing with only "close" values as it does seem "buggy" and the issue doesn't appear in other libraries like lightweight-charts. Including this or something similar can preempt users' head scratching and wasted time.
> 
> ```js
> const eqNaN = (n=0) => isNaN(n) || n==='NaN'
> const ohlcv = ({ open, high, low, close, volume }) => ({
>   open: eqNaN(open) ? close: open,
>   high: eqNaN(high) ? close: high,
>   low: eqNaN(low) ? close: low,
>   close,
>   volume: volume || 0,
> })
> ```

I think it cannot be considered a issue of the library, but of the data

**Comment by liihuu** [comment]
I will consider data validation.

**Comment by fuzzthink** [comment]
Slightly better version, just for reference (not implying it should be used).
```javascript
const invalid = (n=0) => isNaN(n) || typeof(n)==='string'
const ohlcv = ({ open=0, high=0, low=0, close=0, volume=0 }) => ({
  open: invalid(open) ? close : open,
  high: invalid(high) ? close : high,
  low: invalid(low) ? close : low,
  close,
  volume,
})
```

@danielmalencar  I hear you. It can be seen as a data issue and out of scope of the library. I'm almost on the fence on this, but leaning towards resilient data acceptance or at least proper error message out. As it stands, I think this can be considered a bug. The current behavior is all bars disappears without any errors as long as you pan/zoom into 1 "bad" data (it's actual data from iex) point. A library should either provide error message or not behave unexpectedly base on "bad" data. 

Again, just a suggestion, as I'm not pushing too strongly for it since a good portion of users will have to transform their data anyways. But it does not make the library look good when other libraries are more resilient.

**Comment by danielmalencar** [comment]
> Slightly better version, just for reference (not implying it should be used).
> 
> ```js
> const invalid = (n=0) => isNaN(n) || typeof(n)==='string'
> const ohlcv = ({ open=0, high=0, low=0, close=0, volume=0 }) => ({
>   open: invalid(open) ? close : open,
>   high: invalid(high) ? close : high,
>   low: invalid(low) ? close : low,
>   close,
>   volume,
> })
> ```
> 
> @danielmalencar I hear you. It can be seen as a data issue and out of scope of the library. I'm almost on the fence on this, but leaning towards resilient data acceptance or at least proper error message out. As it stands, I think this can be considered a bug. The current behavior is all bars disappears without any errors as long as you pan/zoom into 1 "bad" data (it's actual data from iex) point. A library should either provide error message or not behave unexpectedly base on "bad" data.
> 
> Again, just a suggestion, as I'm not pushing too strongly for it since a good portion of users will have to transform their data anyways. But it does not make the library look good when other libraries are more resilient.

You're right
