### ISSUE TITLE
[BUG] Extend the hover area of marks

### ISSUE THREAD

**Issue by fuzzthink** [liihuu/KLineChart#99]
Currently, in order to select a marking like a ray-line, one needs to know exactly where the marked points are and hover over it. The hover area should be extended to the entire line(s) and a few pixels near the line to make selecting it easier. Bonus, the cursor should be changed to pointer when hover over a marking for good UX as well.

**Comment by danielmalencar** [comment]
True, and this adjustment is quite simple

**Comment by danielmalencar** [comment]
In graphicHelper.js line 95 change :
**return yDif * yDif / (kb.k * kb.k + 1) < DEVIATION * DEVIATION** 
to:
 **return yDif * yDif / (kb.k * kb.k + 10) < DEVIATION * DEVIATION**

`export function checkPointOnStraightLine (point1, point2, targetPoint) {
  if (!targetPoint || !point1 || !point2) {
    return false
  }
  if (point1.x === point2.x) {
    return Math.abs(targetPoint.x - point1.x) < DEVIATION
  }
  const kb = getLinearSlopeIntercept(point1, point2)
  const y = getLinearYFromSlopeIntercept(kb, targetPoint)
  const yDif = Math.abs(y - targetPoint.y)
  return yDif * yDif / (kb.k * kb.k + 10) < DEVIATION * DEVIATION
}
`

**Comment by fuzzthink** [comment]
@danielmalencar Thank you for leading us to where the code is. Aside, you can format code with 
"triple-backQuote(no space)javascript(new line)code(new line)triple-backQuote"

Changing the title to say bug since found bug related to it. For rayLines, in `checkPointOnStraightLine`, it always return `false` inside the `  if (point1.x === point2.x) {` condition since `point1` is "l" and `point2` is "i", so `point1.x` and `point2.x` is undefined, which javascript interprets to be equal. Thus, it will always return `false` here since `targetPoint` is an array of 2 x/y points, not a single point, so `undefined - undefined` is not `< DEVIATION`, hence `false`.

**Comment by liihuu** [comment]
> Currently, in order to select a marking like a ray-line, one needs to know exactly where the marked points are and hover over it. The hover area should be extended to the entire line(s) and a few pixels near the line to make selecting it easier. Bonus, the cursor should be changed to pointer when hover over a marking for good UX as well.

I have tried several methods to check hover. The current inspection plan is the best way I can think of.

**Comment by fuzzthink** [comment]
@liihuu Just want to point out in case you are not aware that there's 2 issues here. 1 is my first comment on extending the hover area of mark/lines. 2 is the bug found in my second comment.

Since I see this library is the best of all open source candlestick charting libraries, I trust your work and your judgement on it being the best you can think of.  But usually fresh eyes are good in spotting alternate solutions. Since extending the hover area should not be something that is too difficult, as danielmalencar believes his PR works for some cases. I think there should be a good solution. I will see if I have time to understand the code more and try to fix the bug (I welcome everyone to try as well). In doing so, I believe we can get a better understanding of how Graphic*.js works and be able to come up with good solutions.

**Comment by fuzzthink** [comment]
Bug fix in https://github.com/liihuu/KLineChart/pull/101 .

**Comment by fuzzthink** [comment]
@liihuu Maybe there's a misunderstanding? Can you please merge in https://github.com/liihuu/KLineChart/pull/100 by @danielmalencar ? This PR fixed the issue of needing the cursor to be exactly on top of the mark lines, which is badly needed since needing the cursor to be precisely on top of the line takes much effort and time. It works well for me. My PR #101 only fixed the missing key param.

**Comment by fuzzthink** [comment]
@liihuu Can you please tell us why https://github.com/liihuu/KLineChart/pull/100 is closed? It is needed to be able to select a line without needing pinpoint hover. I need to go in and modify the code every time I update the library.

If the solution is not what you are looking for, please let us know so we can help make it better.

Thank you.

**Comment by liihuu** [comment]
> @liihuu Can you please tell us why #100 is closed? It is needed to be able to select a line without needing pinpoint hover. I need to go in and modify the code every time I update the library.
> 
> If the solution is not what you are looking for, please let us know so we can help make it better.
> 
> Thank you.

#103
